<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN" xml:lang="zh-CN"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; 基质效应与互换性 – “ivdtools” 使用指引</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./007-干扰研究.html" rel="next">
<link href="./005-不确定度分析.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-644e816dc738f354856c0b4d61e2aec4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "没有结果",
    "search-matching-documents-text": "匹配的文档",
    "search-copy-link-title": "复制搜索链接",
    "search-hide-matches-text": "隐藏其它匹配结果",
    "search-more-match-text": "更多匹配结果",
    "search-more-matches-text": "更多匹配结果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "提交",
    "search-label": "搜索"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/book.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./006-基质效应与互换性.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">基质效应与互换性</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="搜索" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">“ivdtools” 使用指引</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/hiox-tech/ivdtools" title="源代码" class="quarto-navigation-tool px-1" aria-label="源代码"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="搜索"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">欢迎</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./001-ivdtools包总体介绍.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">ivdtools包总体介绍</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./002-分析环境安装与使用.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">分析环境安装与使用</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./003-校准曲线拟合.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">校准曲线拟合</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./004-稳定性研究.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">稳定性研究</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./005-不确定度分析.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">不确定度分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./006-基质效应与互换性.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">基质效应与互换性</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./007-干扰研究.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">干扰研究</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./008-稀释回收与HOOK.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">稀释回收与HOOK</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./009-方法学比较与参考物偏倚.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">方法学比较与参考物偏倚</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./010-质量控制.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">质量控制</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./011-ROC曲线与cutoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">ROC 曲线与 cutoff</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./012-ROC曲线与多元回归.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">ROC 曲线与多元回归</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./013-精密度分析.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">精密度分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./014-线性分析.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">线性分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./015-定性分析与C5C95.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">定性分析与 C5/C95</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./016-检出限定量限.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">检出限/定量限</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./017-参考区间.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">参考区间</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./018-瓶间差.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">瓶间差分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./019-临床样本量计算.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">临床样本量计算</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./020-异常值与正态检验.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">异常值与正态检验</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./021-算法原理简介.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">算法原理简介</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./022-标准对应关系.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">标准对应关系</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./023-IVD适用R包综述.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">IVD 适用 R 包综述</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">目录</h2>
   
  <ul>
  <li><a href="#主要函数" id="toc-主要函数" class="nav-link active" data-scroll-target="#主要函数"><span class="header-section-number">6.1</span> 主要函数</a>
  <ul>
  <li><a href="#输入数据" id="toc-输入数据" class="nav-link" data-scroll-target="#输入数据"><span class="header-section-number">6.1.1</span> 输入数据</a></li>
  <li><a href="#标准设计要求与计算条件" id="toc-标准设计要求与计算条件" class="nav-link" data-scroll-target="#标准设计要求与计算条件"><span class="header-section-number">6.1.2</span> 标准设计要求与计算条件</a></li>
  <li><a href="#ep14-a3deming-回归预测区间" id="toc-ep14-a3deming-回归预测区间" class="nav-link" data-scroll-target="#ep14-a3deming-回归预测区间"><span class="header-section-number">6.1.3</span> EP14-A3：Deming 回归预测区间</a></li>
  <li><a href="#ep30-a预测区间与相对残差" id="toc-ep30-a预测区间与相对残差" class="nav-link" data-scroll-target="#ep30-a预测区间与相对残差"><span class="header-section-number">6.1.4</span> EP30-A：预测区间与相对残差</a></li>
  <li><a href="#ifcc-part-2偏倚差与不确定度" id="toc-ifcc-part-2偏倚差与不确定度" class="nav-link" data-scroll-target="#ifcc-part-2偏倚差与不确定度"><span class="header-section-number">6.1.5</span> IFCC Part 2：偏倚差与不确定度</a></li>
  <li><a href="#ifcc-part-3基于校准有效性的评价" id="toc-ifcc-part-3基于校准有效性的评价" class="nav-link" data-scroll-target="#ifcc-part-3基于校准有效性的评价"><span class="header-section-number">6.1.6</span> IFCC Part 3：基于校准有效性的评价</a></li>
  <li><a href="#分析尺度程序对和参考程序" id="toc-分析尺度程序对和参考程序" class="nav-link" data-scroll-target="#分析尺度程序对和参考程序"><span class="header-section-number">6.1.7</span> 分析尺度、程序对和参考程序</a></li>
  <li><a href="#结果对象与绘图" id="toc-结果对象与绘图" class="nav-link" data-scroll-target="#结果对象与绘图"><span class="header-section-number">6.1.8</span> 结果对象与绘图</a></li>
  </ul></li>
  <li><a href="#分析案例" id="toc-分析案例" class="nav-link" data-scroll-target="#分析案例"><span class="header-section-number">6.2</span> 分析案例</a>
  <ul>
  <li><a href="#clsi-ep14-a3-附录-c-example-c1胆固醇原尺度分析" id="toc-clsi-ep14-a3-附录-c-example-c1胆固醇原尺度分析" class="nav-link" data-scroll-target="#clsi-ep14-a3-附录-c-example-c1胆固醇原尺度分析"><span class="header-section-number">6.2.1</span> CLSI EP14-A3 附录 C Example C1：胆固醇原尺度分析</a></li>
  <li><a href="#clsi-ep14-a3-附录-c-example-c2肌红蛋白-log10-分析" id="toc-clsi-ep14-a3-附录-c-example-c2肌红蛋白-log10-分析" class="nav-link" data-scroll-target="#clsi-ep14-a3-附录-c-example-c2肌红蛋白-log10-分析"><span class="header-section-number">6.2.2</span> CLSI EP14-A3 附录 C Example C2：肌红蛋白 <code>log10</code> 分析</a></li>
  <li><a href="#clsi-ep30-a-附录-b多方法参考物质数据" id="toc-clsi-ep30-a-附录-b多方法参考物质数据" class="nav-link" data-scroll-target="#clsi-ep30-a-附录-b多方法参考物质数据"><span class="header-section-number">6.2.3</span> CLSI EP30-A 附录 B：多方法参考物质数据</a>
  <ul class="collapse">
  <li><a href="#mamb-与-mamd-回归结果" id="toc-mamb-与-mamd-回归结果" class="nav-link" data-scroll-target="#mamb-与-mamd-回归结果"><span class="header-section-number">6.2.3.1</span> MA–MB 与 MA–MD 回归结果</a></li>
  <li><a href="#参考物质预测与相对残差" id="toc-参考物质预测与相对残差" class="nav-link" data-scroll-target="#参考物质预测与相对残差"><span class="header-section-number">6.2.3.2</span> 参考物质预测与相对残差</a></li>
  </ul></li>
  <li><a href="#ifcc-part-2-官方补充材料偏倚差与不确定度" id="toc-ifcc-part-2-官方补充材料偏倚差与不确定度" class="nav-link" data-scroll-target="#ifcc-part-2-官方补充材料偏倚差与不确定度"><span class="header-section-number">6.2.4</span> IFCC Part 2 官方补充材料：偏倚差与不确定度</a></li>
  <li><a href="#ifcc-part-3-官方补充材料基于校准有效性的评价" id="toc-ifcc-part-3-官方补充材料基于校准有效性的评价" class="nav-link" data-scroll-target="#ifcc-part-3-官方补充材料基于校准有效性的评价"><span class="header-section-number">6.2.5</span> IFCC Part 3 官方补充材料：基于校准有效性的评价</a></li>
  <li><a href="#真实应用对照poct-葡萄糖-eqa-材料" id="toc-真实应用对照poct-葡萄糖-eqa-材料" class="nav-link" data-scroll-target="#真实应用对照poct-葡萄糖-eqa-材料"><span class="header-section-number">6.2.6</span> 真实应用对照：POCT 葡萄糖 EQA 材料</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/hiox-tech/ivdtools/issues/new" class="toc-action"><i class="bi bi-github"></i>反馈问题</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">基质效应与互换性</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>本文演示如何使用 ivdtools 包评价参考物质在不同测量程序之间是否具有与天然临床样品一致的数值关系。内容覆盖 CLSI EP14-A3、CLSI EP30-A、IFCC Part 2 和 IFCC Part 3（calibration）四条分析路径，并使用标准原始数据逐项核对计算结果。</p>
<div class="callout callout-style-default callout-important callout-titled" title="使用边界">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">重要</span>使用边界
</div>
</div>
<div class="callout-body-container callout-body">
<p>本文中的标准案例用于说明方法并核对统计计算，不替代标准规定的样本来源、实验设计、运行顺序、随机化、试剂批次、质量控制和记录要求。<code>commutability()</code> 返回的设计检查也不能代替使用者对研究是否符合所选标准作出判断。</p>
<p>EP14 和 EP30 的预测区间评价的是参考物质与临床样品测量关系的统计相容性，不是医学允许误差。IFCC 路径使用的互换性准则必须在分析前规定，不能从观察结果反推。外推、无法评价和不确定（inconclusive）结果应单独报告；结论仅适用于所研究的参考物质、测量程序、分析尺度、浓度范围和实验条件。</p>
</div>
</div>
<p>基质效应是样品中非目标组分对某一测量程序响应的影响；互换性关注的则是参考物质在两个或多个测量程序之间的数值关系，是否与具有代表性的临床样品一致。因此，某种材料不能脱离具体测量程序、浓度范围和使用目的被笼统地称为“互换”或“非互换”。</p>
<p>四条路径回答的问题和判定单位并不相同：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>分析路径</th>
<th>主要问题</th>
<th>判定单位</th>
<th>主要结果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CLSI EP14-A3</td>
<td>处理样品是否遵循临床样品的程序间关系</td>
<td>程序对 × 参考物质</td>
<td>Deming 预测区间与分类</td>
</tr>
<tr class="even">
<td>CLSI EP30-A</td>
<td>参考物质是否适用于一组测量程序</td>
<td>程序对 × 参考物质</td>
<td>预测区间、相对残差与 RMF 对照</td>
</tr>
<tr class="odd">
<td>IFCC Part 2</td>
<td>参考物质偏倚与临床样品偏倚之差是否可接受</td>
<td>程序对 × 参考物质</td>
<td>偏倚差、不确定度与三分类结论</td>
</tr>
<tr class="even">
<td>IFCC Part 3</td>
<td>参考物质重新校准能否降低程序间结果差异</td>
<td>程序集合</td>
<td>校准前后偏倚、IMPBR 与调查诊断</td>
</tr>
</tbody>
</table>
<p>选择分析路径时，应以研究目的、实验设计和预先规定的判定规则为依据。同一组数据不应仅因为某条路径给出更有利的结论而改变方法。</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ivdtools)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="主要函数" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="主要函数"><span class="header-section-number">6.1</span> 主要函数</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>函数</th>
<th>主要用途</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>commutability()</code></td>
<td>按 EP14、EP30、IFCC Part 2 或 IFCC Part 3 路径评价互换性</td>
</tr>
<tr class="even">
<td><code>print()</code></td>
<td>概览分析路径、程序对、设计检查和主要结论</td>
</tr>
<tr class="odd">
<td><code>summary()</code></td>
<td>展开未满足的设计建议、无法分析的程序对及详细结果</td>
</tr>
<tr class="even">
<td><code>plot()</code></td>
<td>绘制临床样品关系、参考物质位置和相应判定边界</td>
</tr>
</tbody>
</table>
<p><code>commutability()</code> 使用长格式重复测量数据，一次调用可以评价一个指定程序对、以某个程序为参考的多个程序对，或数据中的全部两两组合。</p>
<section id="输入数据" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="输入数据"><span class="header-section-number">6.1.1</span> 输入数据</h3>
<p>除 <code>calibration</code> 路径外，每行表示某份临床样品或参考物质在一个测量程序下的一次测量。临床样品和参考物质应使用一致的程序标识、结果单位和分析尺度。</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>字段</th>
<th>含义</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>sample_id</td>
<td>临床样品或参考物质编号</td>
</tr>
<tr class="even">
<td>material_type</td>
<td>材料类别；<code>calibration</code> 路径不需要该字段</td>
</tr>
<tr class="odd">
<td>procedure</td>
<td>测量程序名称</td>
</tr>
<tr class="even">
<td>result</td>
<td>单次测量结果</td>
</tr>
<tr class="odd">
<td>position</td>
<td>IFCC Part 2 中参考物质在运行序列中的位置</td>
</tr>
<tr class="even">
<td>calibration_stage</td>
<td><code>calibration</code> 路径中的 <code>before</code> 或 <code>after</code></td>
</tr>
</tbody>
</table>
<p><code>material_type</code> 自动将 <code>clinical</code>、<code>patient</code> 和 <code>native</code> 识别为临床样品，将 <code>rm</code> 和 <code>reference_material</code> 识别为参考物质，字符大小写不影响识别。其他编码应通过命名字符向量显式映射：</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>type_map <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"patient sample"</span> <span class="ot">=</span> <span class="st">"clinical"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"candidate RM"</span> <span class="ot">=</span> <span class="st">"rm"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  data,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_id =</span> <span class="st">"sample_id"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">material_type =</span> <span class="st">"sample_type"</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure =</span> <span class="st">"procedure"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> <span class="st">"result"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"ep14"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">material_type_map =</span> type_map</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>提供 <code>material_type_map</code> 时，函数完全按该映射处理；未提供时才使用内置自动识别。若存在无法识别的类别，函数列出原始值并提示提供映射，不会将未知材料默认归入某一类。</p>
<p>列参数使用列名字符串，例如：</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  data,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_id =</span> <span class="st">"sample_id"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">material_type =</span> <span class="st">"material_type"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure =</span> <span class="st">"procedure"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> <span class="st">"result"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"ep14"</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="标准设计要求与计算条件" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="标准设计要求与计算条件"><span class="header-section-number">6.1.2</span> 标准设计要求与计算条件</h3>
<p>标准中的样品数量、重复次数、运行位置和程序数量属于研究设计要求或建议，应由使用者在实施和报告阶段主动核对。函数将这些内容保存在 <code>design_checks</code> 中；未满足某项设计检查并不会自动否定仍可计算的统计结果，也不会替使用者宣布研究符合标准。</p>
<p>代码只对完成计算所必需的条件进行验证，例如必需字段、有限数值、可配对的临床样品和参考物质，以及对应方法所需的方差或位置数据。某个程序对无法计算时，原因保存在 <code>analysis_errors</code>；其他可计算的程序对仍可返回。正式分析应同时审阅结果、<code>design_checks</code> 和 <code>analysis_errors</code>。</p>
</section>
<section id="ep14-a3deming-回归预测区间" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="ep14-a3deming-回归预测区间"><span class="header-section-number">6.1.3</span> EP14-A3：Deming 回归预测区间</h3>
<p>设置 <code>approach = "ep14"</code> 后，函数由临床样品重复结果估计两个程序的重复性方差及方差比</p>
<p><span class="math display">\[\lambda=\frac{s_Y^2}{s_X^2},\]</span></p>
<p>再拟合 Deming 关系 <span class="math inline">\(\hat{Y}=\hat{\alpha}+\hat{\beta}X\)</span>。函数在每份参考物质的程序 X 均值处计算预测值、预测标准误和预测区间，并比较程序 Y 的实测均值。常用输出包括 <code>variance_x</code>、<code>variance_y</code>、<code>lambda</code>、<code>intercept</code>、 <code>slope</code>、 <code>predicted_y</code>、<code>prediction_se</code>、<code>lower</code>、<code>upper</code>、<code>extrapolated</code> 和 <code>classification</code>。</p>
<p><code>extrapolated = TRUE</code> 表示参考物质超出临床样品建模范围。函数仍给出数值，但外推结果不应与范围内结果等同解释。</p>
</section>
<section id="ep30-a预测区间与相对残差" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="ep30-a预测区间与相对残差"><span class="header-section-number">6.1.4</span> EP30-A：预测区间与相对残差</h3>
<p>设置 <code>approach = "ep30"</code> 后，函数按 EP30-A 附录 C 传播回归截距、斜率、二者协方差和参考物质重复测量误差，形成参考物质预测区间。<code>rm_set_size</code> 表示作为相关集合共同使用的参考物质数量；彼此独立使用时设为 1。</p>
<p>结果还包括残差标准差 <code>syx</code>、相对残差 <code>relative_residual</code> 及其分类。预测区间与相对残差是两项并列评价，不能用一项替代另一项。参考物质在任一程序上超出临床样品范围时，函数保留计算值，但标准分类标记为 <code>not_evaluable</code>。</p>
</section>
<section id="ifcc-part-2偏倚差与不确定度" class="level3" data-number="6.1.5">
<h3 data-number="6.1.5" class="anchored" data-anchor-id="ifcc-part-2偏倚差与不确定度"><span class="header-section-number">6.1.5</span> IFCC Part 2：偏倚差与不确定度</h3>
<p>设置 <code>approach = "ifcc"</code> 后，必须提供 <code>position</code> 和预先规定的 <code>criterion</code>。<code>bias_model</code> 可选择整个范围的恒定偏倚、局部恒定偏倚或局部线性偏倚：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>模型</th>
<th>解释</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>constant_global</td>
<td>整个浓度范围使用一个临床样品偏倚估计</td>
</tr>
<tr class="even">
<td>constant_local</td>
<td>在每个参考物质附近估计局部恒定偏倚</td>
</tr>
<tr class="odd">
<td>linear_local</td>
<td>在参考物质两侧选取临床样品并估计局部线性偏倚</td>
</tr>
</tbody>
</table>
<p>参考物质偏倚与临床样品偏倚之差为</p>
<p><span class="math display">\[D_{RM}=B_{RM}-B_{CS}.\]</span></p>
<p>其标准不确定度和扩展不确定度为</p>
<p><span class="math display">\[u(D_{RM})=\sqrt{u(B_{RM})^2+u(B_{CS})^2}, \qquad U(D_{RM})=k\,u(D_{RM}).\]</span></p>
<p>若区间 <span class="math inline">\(D_{RM}\pm U(D_{RM})\)</span> 完全位于预设准则 <span class="math inline">\([-C,C]\)</span> 内，则分类为互换；完全位于准则区间外，则分类为非互换；与边界重叠时为不确定。</p>
<p><code>rm_position = "pooled"</code> 按 IFCC Part 2 官方工作簿在每个程序内跨参考物质合并位置均值方差，是默认设置；<code>rm_position = "material_specific"</code> 保留按单个参考物质估计位置变异的兼容模式。</p>
<p><code>results</code> 同时保存 <code>rm_standard_uncertainty</code>、<code>clinical_standard_uncertainty</code>、<code>standard_uncertainty</code> 和 <code>expanded_uncertainty</code>；<code>position_diagnostics</code> 保存每个参考物质的位置数、位置自由度、位置均值标准差及合并结果。</p>
</section>
<section id="ifcc-part-3基于校准有效性的评价" class="level3" data-number="6.1.6">
<h3 data-number="6.1.6" class="anchored" data-anchor-id="ifcc-part-3基于校准有效性的评价"><span class="header-section-number">6.1.6</span> IFCC Part 3：基于校准有效性的评价</h3>
<p>设置 <code>approach = "calibration"</code> 后，不再逐一评价程序对，而是用校准前多个程序结果的截尾均值建立每份临床样品的固定初始靶值，再比较各程序校准前后的中位百分偏倚。程序间最大偏倚范围为</p>
<p><span class="math display">\[IMPBR=\max_p(B_p)-\min_p(B_p).\]</span></p>
<p>该路径必须提供 <code>calibration_stage</code> 和预先规定的百分比 <code>criterion</code>。<code>results</code> 保存校准前后的中位百分偏倚、SD、W(3)、调整后 W(3) 和浓度趋势；<code>diagnostics</code> 保存完整程序集合及显式排除后的 IMPBR；<code>sample_results</code> 保存逐样品偏倚；<code>leave_one_out</code> 仅用于敏感性调查，不会据此自动排除程序。校准后 IMPBR 超过准则时，应调查参考物质互换性、校准模型、测量不精密度和样品特异性干扰。</p>
</section>
<section id="分析尺度程序对和参考程序" class="level3" data-number="6.1.7">
<h3 data-number="6.1.7" class="anchored" data-anchor-id="分析尺度程序对和参考程序"><span class="header-section-number">6.1.7</span> 分析尺度、程序对和参考程序</h3>
<p>EP14 支持 <code>raw</code> 和 <code>log10</code>；EP30 支持 <code>raw</code>、<code>log10</code> 和 <code>ln</code>；IFCC Part 2 支持 <code>raw</code> 和 <code>ln</code>；<code>calibration</code> 只接受 <code>raw</code>。对数变换作用于每条重复结果，再进行样品汇总，因此原始结果必须为正数。分析尺度应在查看结果前确定，并在报告中明确说明。</p>
<p>不指定程序对时，函数评价所有两两组合；也可以指定参考程序或明确的程序对：</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>reference_result <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  data, <span class="st">"sample_id"</span>, <span class="st">"material_type"</span>, <span class="st">"procedure"</span>, <span class="st">"result"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">reference_procedure =</span> <span class="st">"MP1"</span>, <span class="at">approach =</span> <span class="st">"ep14"</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>selected_result <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  data, <span class="st">"sample_id"</span>, <span class="st">"material_type"</span>, <span class="st">"procedure"</span>, <span class="st">"result"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure_pairs =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"MP1"</span>, <span class="st">"MP2"</span>)), <span class="at">approach =</span> <span class="st">"ep14"</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="结果对象与绘图" class="level3" data-number="6.1.8">
<h3 data-number="6.1.8" class="anchored" data-anchor-id="结果对象与绘图"><span class="header-section-number">6.1.8</span> 结果对象与绘图</h3>
<p><code>commutability()</code> 返回 <code>commutability_result</code> 对象。EP14、EP30 和 IFCC Part 2 的 <code>results</code> 以“程序对 × 参考物质”为单位；EP14 和 EP30 的模型保存在 <code>models</code>，EP30 的连续预测区间保存在 <code>prediction_grid</code>，IFCC Part 2 的诊断信息保存在 <code>diagnostics</code> 和 <code>position_diagnostics</code>。<code>calibration</code> 按“程序 × 校准阶段”返回结果，并另存 <code>sample_results</code>、<code>diagnostics</code> 和 <code>leave_one_out</code>。</p>
<p>建议先用 <code>print()</code> 查看整体状态，再用 <code>summary()</code> 审阅设计检查和无法分析的程序对，最后结合 <code>results</code>、诊断表和图形形成报告。正式报告还应保存样品选择、排除记录、重复次数、运行位置、程序方向、分析尺度、预设准则、覆盖因子和软件版本。统计分类不等同于参考物质定值确认、计量溯源确认或产品性能合格判定。</p>
</section>
</section>
<section id="分析案例" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="分析案例"><span class="header-section-number">6.2</span> 分析案例</h2>
<section id="clsi-ep14-a3-附录-c-example-c1胆固醇原尺度分析" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="clsi-ep14-a3-附录-c-example-c1胆固醇原尺度分析"><span class="header-section-number">6.2.1</span> CLSI EP14-A3 附录 C Example C1：胆固醇原尺度分析</h3>
<p>附录 C Example C1 包含 20 份患者样品和 5 份处理样品，两个程序均进行 3 次重复测量，测量项目为胆固醇，单位为 mg/dL。原文 Table C1 将最后两份处理样品都标记为 “d”；数据文件以运行顺序命名为 <code>d_run16</code> 和 <code>d_run07</code>，只为保持材料身份唯一，不改变任何测量值。</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ep14_c1_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/006-基质效应与互换性/std-ep14-appendix-c1.csv"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ep14_c1_data, <span class="dv">6</span>)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  sample_id material_type run_order procedure replicate result position
  &lt;chr&gt;     &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;  &lt;dbl&gt; &lt;lgl&gt;   
1 CS01      clinical             21 A                 1   206. NA      
2 CS01      clinical             21 A                 2   213. NA      
3 CS01      clinical             21 A                 3   205. NA      
4 CS01      clinical             21 B                 1   217. NA      
5 CS01      clinical             21 B                 2   209. NA      
6 CS01      clinical             21 B                 3   220. NA      </code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ep14_c1 <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  ep14_c1_data,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_id =</span> <span class="st">"sample_id"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">material_type =</span> <span class="st">"material_type"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure =</span> <span class="st">"procedure"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> <span class="st">"result"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"ep14"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">scale =</span> <span class="st">"raw"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure_pairs =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>)),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>ep14_c1</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Commutability assessment
Study-design checks: 2 met, 0 unmet. Unmet checks do not invalidate computations; inspect '$design_checks'.
  Approach            : EP14
  Scale               : raw
  Procedure pairs     : 1
  Reference materials : 5
  Procedure pair: A vs B | Reference material: a
    Mean X         : 108.86
    Mean Y         : 110.15
    Predicted Y    : 117.19384
    Residual       : -7.0438387
    Prediction SE  : 3.9893651
    Lower          : 109.13103
    Upper          : 125.25665
    Extrapolated   : FALSE
    Classification : commutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: b
    Mean X         : 123.12333
    Mean Y         : 136.95
    Predicted Y    : 132.71701
    Residual       : 4.2329936
    Prediction SE  : 3.9111051
    Lower          : 124.81237
    Upper          : 140.62164
    Extrapolated   : FALSE
    Classification : commutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: c
    Mean X         : 146.95
    Mean Y         : 175.36667
    Predicted Y    : 158.64821
    Residual       : 16.718461
    Prediction SE  : 3.8114445
    Lower          : 150.94499
    Upper          : 166.35142
    Extrapolated   : FALSE
    Classification : noncommutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: d_run16
    Mean X         : 198.44
    Mean Y         : 215.98333
    Predicted Y    : 214.68615
    Residual       : 1.2971814
    Prediction SE  : 3.740138
    Lower          : 207.12705
    Upper          : 222.24525
    Extrapolated   : FALSE
    Classification : commutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: d_run07
    Mean X         : 222.31667
    Mean Y         : 244.06667
    Predicted Y    : 240.67177
    Residual       : 3.3948989
    Prediction SE  : 3.7763512
    Lower          : 233.03948
    Upper          : 248.30406
    Extrapolated   : FALSE
    Classification : commutable
    procedure_x    : A
    procedure_y    : B</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ep14_c1)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="006-基质效应与互换性_files/figure-html/ep14-c1-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>标准原文还在 <span class="math inline">\(X=145.0\)</span> mg/dL 处给出预测值和预测区间。以下使用 <code>commutability()</code> 返回的模型、临床样品均值和重复性方差，在相同参考点计算这些量。</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>EP14-A3 Example C1：ivdtools 与标准原文结果对照</caption>
<thead>
<tr class="header">
<th style="text-align: left;">标准位置</th>
<th style="text-align: left;">统计量</th>
<th style="text-align: right;">标准结果</th>
<th style="text-align: right;">ivdtools结果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">variance_x</td>
<td style="text-align: right;">15.060</td>
<td style="text-align: right;">15.062097</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">variance_y</td>
<td style="text-align: right;">22.080</td>
<td style="text-align: right;">22.077815</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">lambda</td>
<td style="text-align: right;">1.466</td>
<td style="text-align: right;">1.465786</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">slope</td>
<td style="text-align: right;">1.088</td>
<td style="text-align: right;">1.088327</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">-1.282</td>
<td style="text-align: right;">-1.281415</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">prediction_at_x_145</td>
<td style="text-align: right;">156.500</td>
<td style="text-align: right;">156.525969</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">prediction_se_at_x_145</td>
<td style="text-align: right;">3.820</td>
<td style="text-align: right;">3.818079</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">lower_at_x_145</td>
<td style="text-align: right;">148.800</td>
<td style="text-align: right;">148.809344</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">upper_at_x_145</td>
<td style="text-align: right;">164.200</td>
<td style="text-align: right;">164.242593</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C1</td>
<td style="text-align: left;">noncommutable_count</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>EP14-A3 Example C1：处理样品预测区间分类</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">rm</th>
<th style="text-align: right;">mean_x</th>
<th style="text-align: right;">mean_y</th>
<th style="text-align: right;">predicted_y</th>
<th style="text-align: right;">lower</th>
<th style="text-align: right;">upper</th>
<th style="text-align: left;">extrapolated</th>
<th style="text-align: left;">classification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a</td>
<td style="text-align: right;">108.860</td>
<td style="text-align: right;">110.150</td>
<td style="text-align: right;">117.194</td>
<td style="text-align: right;">109.131</td>
<td style="text-align: right;">125.257</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">123.123</td>
<td style="text-align: right;">136.950</td>
<td style="text-align: right;">132.717</td>
<td style="text-align: right;">124.812</td>
<td style="text-align: right;">140.622</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">c</td>
<td style="text-align: right;">146.950</td>
<td style="text-align: right;">175.367</td>
<td style="text-align: right;">158.648</td>
<td style="text-align: right;">150.945</td>
<td style="text-align: right;">166.351</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">非互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">d_run16</td>
<td style="text-align: right;">198.440</td>
<td style="text-align: right;">215.983</td>
<td style="text-align: right;">214.686</td>
<td style="text-align: right;">207.127</td>
<td style="text-align: right;">222.245</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">d_run07</td>
<td style="text-align: right;">222.317</td>
<td style="text-align: right;">244.067</td>
<td style="text-align: right;">240.672</td>
<td style="text-align: right;">233.039</td>
<td style="text-align: right;">248.304</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">互换</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>处理样品 c 位于预测区间外，其余 4 份位于区间内；没有处理样品发生浓度范围外推。该结论只适用于程序 A–B、原始尺度和本例浓度范围。</p>
</section>
<section id="clsi-ep14-a3-附录-c-example-c2肌红蛋白-log10-分析" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="clsi-ep14-a3-附录-c-example-c2肌红蛋白-log10-分析"><span class="header-section-number">6.2.2</span> CLSI EP14-A3 附录 C Example C2：肌红蛋白 <code>log10</code> 分析</h3>
<p>Example C2 包含 20 份患者样品和 7 份处理样品，测量项目为肌红蛋白，单位为 ng/mL。原始尺度上的差值离散程度随浓度升高而增大，标准因此对每条重复结果作 <code>log10</code> 变换，再拟合 Deming 关系。</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ep14_c2_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/006-基质效应与互换性/std-ep14-appendix-c2.csv"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ep14_c2_data, <span class="dv">6</span>)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  sample_id material_type run_order procedure replicate result position
  &lt;chr&gt;     &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;  &lt;dbl&gt; &lt;lgl&gt;   
1 CS01      clinical              6 A                 1   81.2 NA      
2 CS01      clinical              6 A                 2   77.0 NA      
3 CS01      clinical              6 A                 3   76.4 NA      
4 CS01      clinical              6 B                 1   80.7 NA      
5 CS01      clinical              6 B                 2   82.2 NA      
6 CS01      clinical              6 B                 3   81.3 NA      </code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ep14_c2 <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  ep14_c2_data,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_id =</span> <span class="st">"sample_id"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">material_type =</span> <span class="st">"material_type"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure =</span> <span class="st">"procedure"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> <span class="st">"result"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"ep14"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">scale =</span> <span class="st">"log10"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure_pairs =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>)),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ep14_c2)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Commutability assessment
Study-design checks: 2 met, 0 unmet. Unmet checks do not invalidate computations; inspect '$design_checks'.
  Approach            : EP14
  Scale               : log10
  Procedure pairs     : 1
  Reference materials : 7
  Procedure pair: A vs B | Reference material: a
    Mean X         : 2.8940948
    Mean Y         : 2.8397634
    Predicted Y    : 2.8935335
    Residual       : -0.053770073
    Prediction SE  : 0.020229796
    Lower          : 2.8526475
    Upper          : 2.9344194
    Extrapolated   : FALSE
    Classification : noncommutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: b
    Mean X         : 2.6008874
    Mean Y         : 2.5519334
    Predicted Y    : 2.5995654
    Residual       : -0.047631984
    Prediction SE  : 0.01996673
    Lower          : 2.5592112
    Upper          : 2.6399197
    Extrapolated   : FALSE
    Classification : noncommutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: c
    Mean X         : 3.1955496
    Mean Y         : 3.2183062
    Predicted Y    : 3.1957703
    Residual       : 0.022535935
    Prediction SE  : 0.021016093
    Lower          : 3.1532952
    Upper          : 3.2382454
    Extrapolated   : FALSE
    Classification : commutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: d
    Mean X         : 2.0161898
    Mean Y         : 1.96499
    Predicted Y    : 2.0133509
    Residual       : -0.048360943
    Prediction SE  : 0.020959923
    Lower          : 1.9709893
    Upper          : 2.0557125
    Extrapolated   : FALSE
    Classification : noncommutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: e
    Mean X         : 3.4766983
    Mean Y         : 3.4720027
    Predicted Y    : 3.4776484
    Residual       : -0.0056457436
    Prediction SE  : 0.022172569
    Lower          : 3.432836
    Upper          : 3.5224608
    Extrapolated   : FALSE
    Classification : commutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: f
    Mean X         : 2.3100027
    Mean Y         : 2.2570492
    Predicted Y    : 2.307926
    Residual       : -0.050876857
    Prediction SE  : 0.020214197
    Lower          : 2.2670716
    Upper          : 2.3487804
    Extrapolated   : FALSE
    Classification : noncommutable
    procedure_x    : A
    procedure_y    : B

  Procedure pair: A vs B | Reference material: g
    Mean X         : 1.7036698
    Mean Y         : 1.6448325
    Predicted Y    : 1.7000201
    Residual       : -0.05518756
    Prediction SE  : 0.022243376
    Lower          : 1.6550646
    Upper          : 1.7449756
    Extrapolated   : FALSE
    Classification : noncommutable
    procedure_x    : A
    procedure_y    : B

EP14 model estimates
  Procedure pair: A vs B
    Clinical samples : 20
    Variance X       : 0.00056562731
    Variance Y       : 0.00057048831
    Lambda           : 1.008594
    Intercept        : -0.008069495
    Slope            : 1.0025943
    Slope SE         : 0.010966691
    DF               : 40
    procedure_x      : A
    procedure_y      : B</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>EP14-A3 Example C2：ivdtools 与标准原文结果对照</caption>
<thead>
<tr class="header">
<th style="text-align: left;">标准位置</th>
<th style="text-align: left;">统计量</th>
<th style="text-align: right;">标准结果</th>
<th style="text-align: right;">ivdtools结果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">variance_x</td>
<td style="text-align: right;">0.000566</td>
<td style="text-align: right;">0.0005656</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">variance_y</td>
<td style="text-align: right;">0.000571</td>
<td style="text-align: right;">0.0005705</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">lambda</td>
<td style="text-align: right;">1.009000</td>
<td style="text-align: right;">1.0085940</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">slope</td>
<td style="text-align: right;">1.002600</td>
<td style="text-align: right;">1.0025943</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">-0.008100</td>
<td style="text-align: right;">-0.0080695</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">prediction_at_x_1.64</td>
<td style="text-align: right;">1.635000</td>
<td style="text-align: right;">1.6361851</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">prediction_se_at_x_1.64</td>
<td style="text-align: right;">0.022600</td>
<td style="text-align: right;">0.0225598</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">lower_at_x_1.64</td>
<td style="text-align: right;">1.589000</td>
<td style="text-align: right;">1.5905901</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">upper_at_x_1.64</td>
<td style="text-align: right;">1.681000</td>
<td style="text-align: right;">1.6817802</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP14 C2</td>
<td style="text-align: left;">noncommutable_count</td>
<td style="text-align: right;">5.000000</td>
<td style="text-align: right;">5.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>EP14-A3 Example C2：处理样品在 log10 尺度上的分类</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 18%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">rm</th>
<th style="text-align: right;">mean_x</th>
<th style="text-align: right;">mean_y</th>
<th style="text-align: right;">predicted_y</th>
<th style="text-align: right;">lower</th>
<th style="text-align: right;">upper</th>
<th style="text-align: left;">extrapolated</th>
<th style="text-align: left;">classification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a</td>
<td style="text-align: right;">2.8941</td>
<td style="text-align: right;">2.8398</td>
<td style="text-align: right;">2.8935</td>
<td style="text-align: right;">2.8526</td>
<td style="text-align: right;">2.9344</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">非互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">2.6009</td>
<td style="text-align: right;">2.5519</td>
<td style="text-align: right;">2.5996</td>
<td style="text-align: right;">2.5592</td>
<td style="text-align: right;">2.6399</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">非互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">c</td>
<td style="text-align: right;">3.1955</td>
<td style="text-align: right;">3.2183</td>
<td style="text-align: right;">3.1958</td>
<td style="text-align: right;">3.1533</td>
<td style="text-align: right;">3.2382</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">d</td>
<td style="text-align: right;">2.0162</td>
<td style="text-align: right;">1.9650</td>
<td style="text-align: right;">2.0134</td>
<td style="text-align: right;">1.9710</td>
<td style="text-align: right;">2.0557</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">非互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">e</td>
<td style="text-align: right;">3.4767</td>
<td style="text-align: right;">3.4720</td>
<td style="text-align: right;">3.4776</td>
<td style="text-align: right;">3.4328</td>
<td style="text-align: right;">3.5225</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">f</td>
<td style="text-align: right;">2.3100</td>
<td style="text-align: right;">2.2570</td>
<td style="text-align: right;">2.3079</td>
<td style="text-align: right;">2.2671</td>
<td style="text-align: right;">2.3488</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">非互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">g</td>
<td style="text-align: right;">1.7037</td>
<td style="text-align: right;">1.6448</td>
<td style="text-align: right;">1.7000</td>
<td style="text-align: right;">1.6551</td>
<td style="text-align: right;">1.7450</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">非互换</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ep14_c2)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="006-基质效应与互换性_files/figure-html/ep14-c2-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>处理样品 a、b、d、f、g 为非互换，c 和 e 为互换，共 5 份非互换；没有处理样品发生外推。</p>
</section>
<section id="clsi-ep30-a-附录-b多方法参考物质数据" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="clsi-ep30-a-附录-b多方法参考物质数据"><span class="header-section-number">6.2.3</span> CLSI EP30-A 附录 B：多方法参考物质数据</h3>
<p>EP30-A 附录 B 给出 25 份临床样品、7 个候选参考物质、10 个测量方法和每个组合 3 次重复测量。</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>ep30_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/006-基质效应与互换性/std-ep30-appendix-b.csv"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="mamb-与-mamd-回归结果" class="level4" data-number="6.2.3.1">
<h4 data-number="6.2.3.1" class="anchored" data-anchor-id="mamb-与-mamd-回归结果"><span class="header-section-number">6.2.3.1</span> MA–MB 与 MA–MD 回归结果</h4>
<p>以下直接使用 <code>approach = "ep30"</code>。7 份候选参考物质在示例中彼此独立使用，因此 <code>rm_set_size = 1</code>；函数不会把材料总数 7 自动当成相关集合大小。</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>ep30_result <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  ep30_raw,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_id =</span> <span class="st">"specimen"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">material_type =</span> <span class="st">"type"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure =</span> <span class="st">"method"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> <span class="st">"result"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"ep30"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">scale =</span> <span class="st">"raw"</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure_pairs =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"MA"</span>, <span class="st">"MB"</span>), <span class="fu">c</span>(<span class="st">"MA"</span>, <span class="st">"MD"</span>)),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">rm_set_size =</span> <span class="dv">1</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">relative_residual_limit =</span> <span class="dv">2</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>ep30_result</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Commutability assessment
Study-design checks: 8 met, 0 unmet. Unmet checks do not invalidate computations; inspect '$design_checks'.
  Approach            : EP30
  Scale               : raw
  Procedure pairs     : 2
  Reference materials : 14
  Procedure pair: MA vs MB | Reference material: RMA
    Mean X                           : 12.4
    Mean Y                           : 14.3
    Predicted Y                      : 15.576069
    Residual                         : -1.2760688
    Prediction SE                    : 1.8530797
    Lower                            : 11.944099
    Upper                            : 19.208038
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.1890275
    Relative residual                : 1.0732038
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MB
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MB | Reference material: RMB
    Mean X                           : 24.1
    Mean Y                           : 26.9
    Predicted Y                      : 26.829327
    Residual                         : 0.070672943
    Prediction SE                    : 1.8454797
    Lower                            : 23.212253
    Upper                            : 30.446401
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.1890275
    Relative residual                : -0.059437604
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MB
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MB | Reference material: RMC
    Mean X                           : 35.4
    Mean Y                           : 37
    Predicted Y                      : 37.697859
    Residual                         : -0.69785851
    Prediction SE                    : 1.8688251
    Lower                            : 34.035029
    Upper                            : 41.360688
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.1890275
    Relative residual                : 0.58691538
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MB
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MB | Reference material: RMD
    Mean X                           : 42.2
    Mean Y                           : 41.7
    Predicted Y                      : 44.238214
    Residual                         : -2.5382137
    Prediction SE                    : 1.8969998
    Lower                            : 40.520162
    Upper                            : 47.956265
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.1890275
    Relative residual                : 2.1346973
    Relative-residual limit          : 2
    Relative-residual classification : noncommutable
    procedure_x                      : MA
    procedure_y                      : MB
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MB | Reference material: RME
    Mean X                           : 15.3
    Mean Y                           : 19
    Predicted Y                      : 18.365338
    Residual                         : 0.63466204
    Prediction SE                    : 1.8481767
    Lower                            : 14.742978
    Upper                            : 21.987698
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.1890275
    Relative residual                : -0.53376567
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MB
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MB | Reference material: RMF
    Mean X                           : 21
    Mean Y                           : 20
    Predicted Y                      : 23.847695
    Residual                         : -3.8476945
    Prediction SE                    : 1.8443328
    Lower                            : 20.232869
    Upper                            : 27.46252
    Extrapolated                     : FALSE
    Prediction classification        : noncommutable
    Sy.x                             : 1.1890275
    Relative residual                : 3.2360014
    Relative-residual limit          : 2
    Relative-residual classification : noncommutable
    procedure_x                      : MA
    procedure_y                      : MB
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : noncommutable

  Procedure pair: MA vs MB | Reference material: RMG
    Mean X                           : 17
    Mean Y                           : 21.1
    Predicted Y                      : 20.000427
    Residual                         : 1.0995732
    Prediction SE                    : 1.8462245
    Lower                            : 16.381893
    Upper                            : 23.61896
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.1890275
    Relative residual                : -0.9247669
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MB
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MD | Reference material: RMA
    Mean X                           : 12.4
    Mean Y                           : 11.4
    Predicted Y                      : 10.746146
    Residual                         : 0.65385407
    Prediction SE                    : 1.8882069
    Lower                            : 7.0453283
    Upper                            : 14.446964
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.0324006
    Relative residual                : -0.63333369
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MD
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MD | Reference material: RMB
    Mean X                           : 24.1
    Mean Y                           : 19.9
    Predicted Y                      : 20.509565
    Residual                         : -0.60956453
    Prediction SE                    : 1.8825915
    Lower                            : 16.819753
    Upper                            : 24.199376
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.0324006
    Relative residual                : 0.59043412
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MD
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MD | Reference material: RMC
    Mean X                           : 35.4
    Mean Y                           : 29.6
    Predicted Y                      : 29.939191
    Residual                         : -0.33919104
    Prediction SE                    : 1.8998608
    Lower                            : 26.215532
    Upper                            : 33.66285
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.0324006
    Relative residual                : 0.32854596
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MD
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MD | Reference material: RMD
    Mean X                           : 42.2
    Mean Y                           : 34.6
    Predicted Y                      : 35.613657
    Residual                         : -1.0136566
    Prediction SE                    : 1.9207804
    Lower                            : 31.848996
    Upper                            : 39.378317
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.0324006
    Relative residual                : 0.98184422
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MD
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MD | Reference material: RME
    Mean X                           : 15.3
    Mean Y                           : 13.2
    Predicted Y                      : 13.166139
    Residual                         : 0.033861426
    Prediction SE                    : 1.8845835
    Lower                            : 9.4724228
    Upper                            : 16.859854
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.0324006
    Relative residual                : -0.032798728
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MD
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable

  Procedure pair: MA vs MD | Reference material: RMF
    Mean X                           : 21
    Mean Y                           : 24.9
    Predicted Y                      : 17.922676
    Residual                         : 6.9773242
    Prediction SE                    : 1.8817446
    Lower                            : 14.234524
    Upper                            : 21.610828
    Extrapolated                     : FALSE
    Prediction classification        : noncommutable
    Sy.x                             : 1.0324006
    Relative residual                : -6.7583496
    Relative-residual limit          : 2
    Relative-residual classification : noncommutable
    procedure_x                      : MA
    procedure_y                      : MD
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : noncommutable

  Procedure pair: MA vs MD | Reference material: RMG
    Mean X                           : 17
    Mean Y                           : 14.7
    Predicted Y                      : 14.584755
    Residual                         : 0.11524505
    Prediction SE                    : 1.8831415
    Lower                            : 10.893865
    Upper                            : 18.275645
    Extrapolated                     : FALSE
    Prediction classification        : commutable
    Sy.x                             : 1.0324006
    Relative residual                : -0.11162823
    Relative-residual limit          : 2
    Relative-residual classification : commutable
    procedure_x                      : MA
    procedure_y                      : MD
    critical_value                   : 1.959964
    rm_set_size                      : 1
    classification                   : commutable</code></pre>
</div>
</div>
</section>
<section id="参考物质预测与相对残差" class="level4" data-number="6.2.3.2">
<h4 data-number="6.2.3.2" class="anchored" data-anchor-id="参考物质预测与相对残差"><span class="header-section-number">6.2.3.2</span> 参考物质预测与相对残差</h4>
<p>EP30 Table 1 的相对残差为参考物质到回归线的距离除以临床样品回归标准误。<code>commutability()</code> 按原表符号方向返回 <code>预测值 − 实测值</code>，并按示例使用 <span class="math inline">\(n-1\)</span> 作为 <span class="math inline">\(S_{y.x}\)</span> 的分母自由度。预测区间另按附录 C16～C20 计算。</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>EP30-A 附录 B Table 1：回归参数和相对残差对照</caption>
<thead>
<tr class="header">
<th style="text-align: left;">标准位置</th>
<th style="text-align: left;">统计量</th>
<th style="text-align: right;">标准结果</th>
<th style="text-align: right;">ivdtools结果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">3.660</td>
<td style="text-align: right;">3.6495</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">slope</td>
<td style="text-align: right;">0.961</td>
<td style="text-align: right;">0.9618</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">syx</td>
<td style="text-align: right;">1.188</td>
<td style="text-align: right;">1.1890</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">RMA</td>
<td style="text-align: right;">1.088</td>
<td style="text-align: right;">1.0732</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">RMB</td>
<td style="text-align: right;">-0.117</td>
<td style="text-align: right;">-0.0594</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">RMC</td>
<td style="text-align: right;">0.601</td>
<td style="text-align: right;">0.5869</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">RMD</td>
<td style="text-align: right;">2.164</td>
<td style="text-align: right;">2.1347</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">RME</td>
<td style="text-align: right;">-0.523</td>
<td style="text-align: right;">-0.5338</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">RMF</td>
<td style="text-align: right;">3.241</td>
<td style="text-align: right;">3.2360</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MB</td>
<td style="text-align: left;">RMG</td>
<td style="text-align: right;">-0.923</td>
<td style="text-align: right;">-0.9248</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">0.396</td>
<td style="text-align: right;">0.3986</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">slope</td>
<td style="text-align: right;">0.834</td>
<td style="text-align: right;">0.8345</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">syx</td>
<td style="text-align: right;">1.033</td>
<td style="text-align: right;">1.0324</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">RMA</td>
<td style="text-align: right;">-0.603</td>
<td style="text-align: right;">-0.6333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">RMB</td>
<td style="text-align: right;">0.518</td>
<td style="text-align: right;">0.5904</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">RMC</td>
<td style="text-align: right;">0.326</td>
<td style="text-align: right;">0.3285</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">RMD</td>
<td style="text-align: right;">0.997</td>
<td style="text-align: right;">0.9818</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">RME</td>
<td style="text-align: right;">-0.021</td>
<td style="text-align: right;">-0.0328</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">RMF</td>
<td style="text-align: right;">-6.758</td>
<td style="text-align: right;">-6.7583</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP30 MA-MD</td>
<td style="text-align: left;">RMG</td>
<td style="text-align: right;">-0.066</td>
<td style="text-align: right;">-0.1116</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>按 <span class="math inline">\(\pm2S_{y.x}\)</span> 规则，MA–MD 中 RMF 为非互换；MA–MB 中 RMD 和 RMF 超出界限。RMD 在 MA–MB 的 95% 预测区间方法下仍为互换，说明边界附近的材料可能因评价规则不同而分类不同。</p>
<p>预测区间与相对残差方法对 MA–MB 中 RMD 的分类不同：前者判为互换，后者判为非互换。这是评价规则造成的边界差异，不应把两列合并成一个未经定义的“最终分类”。</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>EP30-A 附录 B：预测区间与相对残差分类</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">程序对</th>
<th style="text-align: left;">参考物质</th>
<th style="text-align: right;">预测值</th>
<th style="text-align: right;">下限</th>
<th style="text-align: right;">上限</th>
<th style="text-align: left;">区间判定</th>
<th style="text-align: right;">相对残差</th>
<th style="text-align: left;">残差判定</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">MA vs MB</td>
<td style="text-align: left;">RMA</td>
<td style="text-align: right;">15.576</td>
<td style="text-align: right;">11.944</td>
<td style="text-align: right;">19.208</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">1.073</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA vs MB</td>
<td style="text-align: left;">RMB</td>
<td style="text-align: right;">26.829</td>
<td style="text-align: right;">23.212</td>
<td style="text-align: right;">30.446</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">-0.059</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MA vs MB</td>
<td style="text-align: left;">RMC</td>
<td style="text-align: right;">37.698</td>
<td style="text-align: right;">34.035</td>
<td style="text-align: right;">41.361</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">0.587</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA vs MB</td>
<td style="text-align: left;">RMD</td>
<td style="text-align: right;">44.238</td>
<td style="text-align: right;">40.520</td>
<td style="text-align: right;">47.956</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">2.135</td>
<td style="text-align: left;">非互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MA vs MB</td>
<td style="text-align: left;">RME</td>
<td style="text-align: right;">18.365</td>
<td style="text-align: right;">14.743</td>
<td style="text-align: right;">21.988</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">-0.534</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA vs MB</td>
<td style="text-align: left;">RMF</td>
<td style="text-align: right;">23.848</td>
<td style="text-align: right;">20.233</td>
<td style="text-align: right;">27.463</td>
<td style="text-align: left;">非互换</td>
<td style="text-align: right;">3.236</td>
<td style="text-align: left;">非互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MA vs MB</td>
<td style="text-align: left;">RMG</td>
<td style="text-align: right;">20.000</td>
<td style="text-align: right;">16.382</td>
<td style="text-align: right;">23.619</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">-0.925</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA vs MD</td>
<td style="text-align: left;">RMA</td>
<td style="text-align: right;">10.746</td>
<td style="text-align: right;">7.045</td>
<td style="text-align: right;">14.447</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">-0.633</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MA vs MD</td>
<td style="text-align: left;">RMB</td>
<td style="text-align: right;">20.510</td>
<td style="text-align: right;">16.820</td>
<td style="text-align: right;">24.199</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">0.590</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA vs MD</td>
<td style="text-align: left;">RMC</td>
<td style="text-align: right;">29.939</td>
<td style="text-align: right;">26.216</td>
<td style="text-align: right;">33.663</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">0.329</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MA vs MD</td>
<td style="text-align: left;">RMD</td>
<td style="text-align: right;">35.614</td>
<td style="text-align: right;">31.849</td>
<td style="text-align: right;">39.378</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">0.982</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA vs MD</td>
<td style="text-align: left;">RME</td>
<td style="text-align: right;">13.166</td>
<td style="text-align: right;">9.472</td>
<td style="text-align: right;">16.860</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">-0.033</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MA vs MD</td>
<td style="text-align: left;">RMF</td>
<td style="text-align: right;">17.923</td>
<td style="text-align: right;">14.235</td>
<td style="text-align: right;">21.611</td>
<td style="text-align: left;">非互换</td>
<td style="text-align: right;">-6.758</td>
<td style="text-align: left;">非互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA vs MD</td>
<td style="text-align: left;">RMG</td>
<td style="text-align: right;">14.585</td>
<td style="text-align: right;">10.894</td>
<td style="text-align: right;">18.276</td>
<td style="text-align: left;">互换</td>
<td style="text-align: right;">-0.112</td>
<td style="text-align: left;">互换</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ep30_result)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="006-基质效应与互换性_files/figure-html/ep30-prediction-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ep30_result, <span class="at">method =</span> <span class="st">"relative_residual"</span>)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="006-基质效应与互换性_files/figure-html/ep30-relative-residual-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="ifcc-part-2-官方补充材料偏倚差与不确定度" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="ifcc-part-2-官方补充材料偏倚差与不确定度"><span class="header-section-number">6.2.4</span> IFCC Part 2 官方补充材料：偏倚差与不确定度</h3>
<p>IFCC Part 2 官方工作簿初始包含 50 份临床样品和 5 个参考物质。按补充说明排除 CS21 的全部结果以及 CS6 在 MPx 的第 3 次重复后，49 份临床样品进入分析。参考物质在每个程序下包含 5 个位置、每个位置 3 次重复；分析使用自然对数尺度、准则 <span class="math inline">\(C=0.12\)</span> 和覆盖因子 <span class="math inline">\(k=1.9\)</span>。</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ifcc_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/006-基质效应与互换性/std-ifcc-part2-example.csv"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ifcc_data<span class="sc">$</span>material_type, ifcc_data<span class="sc">$</span>procedure)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          
           MPx MPy
  clinical 146 147
  rm        75  75</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ifcc_result <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  ifcc_data,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_id =</span> <span class="st">"sample_id"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">material_type =</span> <span class="st">"material_type"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure =</span> <span class="st">"procedure"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> <span class="st">"result"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">position =</span> <span class="st">"position"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"ifcc"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">scale =</span> <span class="st">"ln"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure_pairs =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"MPx"</span>, <span class="st">"MPy"</span>)),</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">criterion =</span> <span class="fl">0.12</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">bias_model =</span> <span class="st">"constant_global"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">coverage_factor =</span> <span class="fl">1.9</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">rm_position =</span> <span class="st">"pooled"</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>ifcc_result</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Commutability assessment
Study-design checks: 4 met, 0 unmet. Unmet checks do not invalidate computations; inspect '$design_checks'.
  Approach            : IFCC
  Scale               : ln
  Procedure pairs     : 1
  Reference materials : 5
  Procedure pair: MPx vs MPy | Reference material: RM1
    RM coordinate                 : 2.7755556
    RM bias                       : 0.33925926
    Clinical bias                 : 0.18095238
    Difference in bias            : 0.15830688
    RM standard uncertainty       : 0.037626363
    Clinical standard uncertainty : 0.015516499
    Standard uncertainty          : 0.040700184
    Expanded uncertainty          : 0.077330349
    Lower                         : 0.080976529
    Upper                         : 0.23563723
    Criterion                     : 0.12
    Clinical samples              : 49
    Classification                : inconclusive
    procedure_x                   : MPx
    procedure_y                   : MPy
    position_mean_sd_x            : 0.067355047
    position_mean_sd_y            : 0.050418387
    positions_x                   : 5
    positions_y                   : 5
    position_pooling              : pooled

  Procedure pair: MPx vs MPy | Reference material: RM2
    RM coordinate                 : 3.3097037
    RM bias                       : 0.12903704
    Clinical bias                 : 0.18095238
    Difference in bias            : -0.051915344
    RM standard uncertainty       : 0.037626363
    Clinical standard uncertainty : 0.015516499
    Standard uncertainty          : 0.040700184
    Expanded uncertainty          : 0.077330349
    Lower                         : -0.12924569
    Upper                         : 0.025415005
    Criterion                     : 0.12
    Clinical samples              : 49
    Classification                : inconclusive
    procedure_x                   : MPx
    procedure_y                   : MPy
    position_mean_sd_x            : 0.067355047
    position_mean_sd_y            : 0.050418387
    positions_x                   : 5
    positions_y                   : 5
    position_pooling              : pooled

  Procedure pair: MPx vs MPy | Reference material: RM3
    RM coordinate                 : 5.5979259
    RM bias                       : 0.16
    Clinical bias                 : 0.18095238
    Difference in bias            : -0.020952381
    RM standard uncertainty       : 0.037626363
    Clinical standard uncertainty : 0.015516499
    Standard uncertainty          : 0.040700184
    Expanded uncertainty          : 0.077330349
    Lower                         : -0.09828273
    Upper                         : 0.056377968
    Criterion                     : 0.12
    Clinical samples              : 49
    Classification                : commutable
    procedure_x                   : MPx
    procedure_y                   : MPy
    position_mean_sd_x            : 0.067355047
    position_mean_sd_y            : 0.050418387
    positions_x                   : 5
    positions_y                   : 5
    position_pooling              : pooled

  Procedure pair: MPx vs MPy | Reference material: RM4
    RM coordinate                 : 1.607037
    RM bias                       : 0.073333333
    Clinical bias                 : 0.18095238
    Difference in bias            : -0.10761905
    RM standard uncertainty       : 0.037626363
    Clinical standard uncertainty : 0.015516499
    Standard uncertainty          : 0.040700184
    Expanded uncertainty          : 0.077330349
    Lower                         : -0.1849494
    Upper                         : -0.030288699
    Criterion                     : 0.12
    Clinical samples              : 49
    Classification                : inconclusive
    procedure_x                   : MPx
    procedure_y                   : MPy
    position_mean_sd_x            : 0.067355047
    position_mean_sd_y            : 0.050418387
    positions_x                   : 5
    positions_y                   : 5
    position_pooling              : pooled

  Procedure pair: MPx vs MPy | Reference material: RM5
    RM coordinate                 : 4.4167407
    RM bias                       : 0.85866667
    Clinical bias                 : 0.18095238
    Difference in bias            : 0.67771429
    RM standard uncertainty       : 0.037626363
    Clinical standard uncertainty : 0.015516499
    Standard uncertainty          : 0.040700184
    Expanded uncertainty          : 0.077330349
    Lower                         : 0.60038394
    Upper                         : 0.75504463
    Criterion                     : 0.12
    Clinical samples              : 49
    Classification                : noncommutable
    procedure_x                   : MPx
    procedure_y                   : MPy
    position_mean_sd_x            : 0.067355047
    position_mean_sd_y            : 0.050418387
    positions_x                   : 5
    positions_y                   : 5
    position_pooling              : pooled</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>IFCC Part 2：ivdtools 与官方工作簿材料级结果对照</caption>
<thead>
<tr class="header">
<th style="text-align: left;">标准位置</th>
<th style="text-align: left;">统计量</th>
<th style="text-align: left;">标准结果</th>
<th style="text-align: left;">ivdtools结果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM1</td>
<td style="text-align: left;">偏倚差 D_RM</td>
<td style="text-align: left;">0.1583069</td>
<td style="text-align: left;">0.1583069</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM1</td>
<td style="text-align: left;">扩展不确定度 U(D_RM)</td>
<td style="text-align: left;">0.0773303</td>
<td style="text-align: left;">0.0773303</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM1</td>
<td style="text-align: left;">区间下限</td>
<td style="text-align: left;">0.0809765</td>
<td style="text-align: left;">0.0809765</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM1</td>
<td style="text-align: left;">区间上限</td>
<td style="text-align: left;">0.2356372</td>
<td style="text-align: left;">0.2356372</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM1</td>
<td style="text-align: left;">分类</td>
<td style="text-align: left;">不确定</td>
<td style="text-align: left;">不确定</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM2</td>
<td style="text-align: left;">偏倚差 D_RM</td>
<td style="text-align: left;">-0.0519153</td>
<td style="text-align: left;">-0.0519153</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM2</td>
<td style="text-align: left;">扩展不确定度 U(D_RM)</td>
<td style="text-align: left;">0.0773303</td>
<td style="text-align: left;">0.0773303</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM2</td>
<td style="text-align: left;">区间下限</td>
<td style="text-align: left;">-0.1292457</td>
<td style="text-align: left;">-0.1292457</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM2</td>
<td style="text-align: left;">区间上限</td>
<td style="text-align: left;">0.0254150</td>
<td style="text-align: left;">0.0254150</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM2</td>
<td style="text-align: left;">分类</td>
<td style="text-align: left;">不确定</td>
<td style="text-align: left;">不确定</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM3</td>
<td style="text-align: left;">偏倚差 D_RM</td>
<td style="text-align: left;">-0.0209524</td>
<td style="text-align: left;">-0.0209524</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM3</td>
<td style="text-align: left;">扩展不确定度 U(D_RM)</td>
<td style="text-align: left;">0.0773303</td>
<td style="text-align: left;">0.0773303</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM3</td>
<td style="text-align: left;">区间下限</td>
<td style="text-align: left;">-0.0982827</td>
<td style="text-align: left;">-0.0982827</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM3</td>
<td style="text-align: left;">区间上限</td>
<td style="text-align: left;">0.0563780</td>
<td style="text-align: left;">0.0563780</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM3</td>
<td style="text-align: left;">分类</td>
<td style="text-align: left;">互换</td>
<td style="text-align: left;">互换</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM4</td>
<td style="text-align: left;">偏倚差 D_RM</td>
<td style="text-align: left;">-0.1076190</td>
<td style="text-align: left;">-0.1076190</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM4</td>
<td style="text-align: left;">扩展不确定度 U(D_RM)</td>
<td style="text-align: left;">0.0773303</td>
<td style="text-align: left;">0.0773303</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM4</td>
<td style="text-align: left;">区间下限</td>
<td style="text-align: left;">-0.1849494</td>
<td style="text-align: left;">-0.1849494</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM4</td>
<td style="text-align: left;">区间上限</td>
<td style="text-align: left;">-0.0302887</td>
<td style="text-align: left;">-0.0302887</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM4</td>
<td style="text-align: left;">分类</td>
<td style="text-align: left;">不确定</td>
<td style="text-align: left;">不确定</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM5</td>
<td style="text-align: left;">偏倚差 D_RM</td>
<td style="text-align: left;">0.6777143</td>
<td style="text-align: left;">0.6777143</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM5</td>
<td style="text-align: left;">扩展不确定度 U(D_RM)</td>
<td style="text-align: left;">0.0773303</td>
<td style="text-align: left;">0.0773303</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM5</td>
<td style="text-align: left;">区间下限</td>
<td style="text-align: left;">0.6003839</td>
<td style="text-align: left;">0.6003839</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / RM5</td>
<td style="text-align: left;">区间上限</td>
<td style="text-align: left;">0.7550446</td>
<td style="text-align: left;">0.7550446</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / RM5</td>
<td style="text-align: left;">分类</td>
<td style="text-align: left;">非互换</td>
<td style="text-align: left;">非互换</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>IFCC Part 2：不确定度分量与官方工作簿对照</caption>
<colgroup>
<col style="width: 45%">
<col style="width: 25%">
<col style="width: 13%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">标准位置</th>
<th style="text-align: left;">统计量</th>
<th style="text-align: right;">标准结果</th>
<th style="text-align: right;">ivdtools结果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / uncertainty components</td>
<td style="text-align: left;">临床样品平均偏倚</td>
<td style="text-align: right;">0.18095238</td>
<td style="text-align: right;">0.18095238</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / uncertainty components</td>
<td style="text-align: left;">MPx 合并位置均值 SD</td>
<td style="text-align: right;">0.06735505</td>
<td style="text-align: right;">0.06735505</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / uncertainty components</td>
<td style="text-align: left;">MPy 合并位置均值 SD</td>
<td style="text-align: right;">0.05041839</td>
<td style="text-align: right;">0.05041839</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / uncertainty components</td>
<td style="text-align: left;">参考物质标准不确定度</td>
<td style="text-align: right;">0.03762636</td>
<td style="text-align: right;">0.03762636</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / uncertainty components</td>
<td style="text-align: left;">临床样品标准不确定度</td>
<td style="text-align: right;">0.01551650</td>
<td style="text-align: right;">0.01551650</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 2 / uncertainty components</td>
<td style="text-align: left;">偏倚差标准不确定度</td>
<td style="text-align: right;">0.04070018</td>
<td style="text-align: right;">0.04070018</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 2 / uncertainty components</td>
<td style="text-align: left;">偏倚差扩展不确定度</td>
<td style="text-align: right;">0.07733035</td>
<td style="text-align: right;">0.07733035</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ifcc_result)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="006-基质效应与互换性_files/figure-html/ifcc-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>RM3 的分类依赖于按官方方式跨参考物质合并位置均值方差；若改为逐参考物质位置方差，算法和分类口径都会改变，因此正式报告必须记录 <code>rm_position</code> 设置。</p>
</section>
<section id="ifcc-part-3-官方补充材料基于校准有效性的评价" class="level3" data-number="6.2.5">
<h3 data-number="6.2.5" class="anchored" data-anchor-id="ifcc-part-3-官方补充材料基于校准有效性的评价"><span class="header-section-number">6.2.5</span> IFCC Part 3 官方补充材料：基于校准有效性的评价</h3>
<p>IFCC Part 3 官方案例包含 40 份临床样品和 7 个测量程序。Table S1 是按制造商原校准方案得到的结果；每份临床样品的初始靶值为 7 个程序结果排序后删除最大值和最小值、再对中间 5 个值取均值。Table S2 是使用两水平候选参考物质重新校准后的结果，但仍使用 Table S1 的初始靶值，不能根据校准后结果重新定靶。</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ifcc_part3_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/006-基质效应与互换性/std-ifcc-part3-example.csv"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  ifcc_part3_data<span class="sc">$</span>calibration_stage,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  ifcc_part3_data<span class="sc">$</span>procedure</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        
         MP1 MP2 MP3 MP4 MP5 MP6 MP7
  after   40  40  40  40  40  40  40
  before  40  40  40  40  40  40  40</code></pre>
</div>
</div>
<p>先评价全部 7 个程序。<code>criterion = 6</code> 是论文示例预先规定的 IMPBR 百分比准则；<code>w3_reference_procedure = "MP1"</code> 按原文使用 MP1 的 SD/W(3) 比例调整各程序的 W(3)。</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>ifcc_part3_result <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  ifcc_part3_data,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_id =</span> <span class="st">"sample_id"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure =</span> <span class="st">"procedure"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> <span class="st">"result"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"calibration"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">calibration_stage =</span> <span class="st">"calibration_stage"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">criterion =</span> <span class="dv">6</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">w3_reference_procedure =</span> <span class="st">"MP1"</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>ifcc_part3_excluding_mp6 <span class="ot">&lt;-</span> <span class="fu">commutability</span>(</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  ifcc_part3_data,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_id =</span> <span class="st">"sample_id"</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">procedure =</span> <span class="st">"procedure"</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">result =</span> <span class="st">"result"</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"calibration"</span>,</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">calibration_stage =</span> <span class="st">"calibration_stage"</span>,</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">criterion =</span> <span class="dv">6</span>,</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">exclude_procedures =</span> <span class="st">"MP6"</span>,</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">w3_reference_procedure =</span> <span class="st">"MP1"</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>ifcc_part3_excluding_mp6</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Commutability assessment
Study-design checks: 4 met, 0 unmet. Unmet checks do not invalidate computations; inspect '$design_checks'.
  Approach            : CALIBRATION (IFCC PART 3)
  Scale               : raw
  Procedures          : 7
  Clinical samples    : 40
  IMPBR criterion (%) : 6
  Stage: before | Procedure: MP1
    Clinical samples             : 40
    Median bias (%)              : -0.38910506
    Bias SD (%)                  : 4.0149558
    Adjusted W(3) (%)            : 4.0149558
    Included after investigation : TRUE
    w3_percent                   : 11.18415
    trend_intercept              : 1.288401
    trend_slope                  : -0.019331579
    trend_p_value                : 0.54012483

  Stage: before | Procedure: MP2
    Clinical samples             : 40
    Median bias (%)              : 9.5282484
    Bias SD (%)                  : 5.7222879
    Adjusted W(3) (%)            : 5.5726509
    Included after investigation : TRUE
    w3_percent                   : 15.5233
    trend_intercept              : 5.3027017
    trend_slope                  : 0.060976356
    trend_p_value                : 0.17087519

  Stage: before | Procedure: MP3
    Clinical samples             : 40
    Median bias (%)              : 20.680902
    Bias SD (%)                  : 9.5434313
    Adjusted W(3) (%)            : 5.9037259
    Included after investigation : TRUE
    w3_percent                   : 16.44555
    trend_intercept              : 24.218286
    trend_slope                  : -0.029099244
    trend_p_value                : 0.69847835

  Stage: before | Procedure: MP4
    Clinical samples             : 40
    Median bias (%)              : 46.552662
    Bias SD (%)                  : 6.7290862
    Adjusted W(3) (%)            : 5.8855004
    Included after investigation : TRUE
    w3_percent                   : 16.394781
    trend_intercept              : 61.15902
    trend_slope                  : -0.20881729
    trend_p_value                : 7.623953e-06

  Stage: before | Procedure: MP5
    Clinical samples             : 40
    Median bias (%)              : -30.046827
    Bias SD (%)                  : 4.5852825
    Adjusted W(3) (%)            : 3.4941653
    Included after investigation : TRUE
    w3_percent                   : 9.7334245
    trend_intercept              : -30.931755
    trend_slope                  : 0.021966809
    trend_p_value                : 0.54217093

  Stage: before | Procedure: MP6
    Clinical samples             : 40
    Median bias (%)              : -19.447183
    Bias SD (%)                  : 5.2950133
    Adjusted W(3) (%)            : 3.9604755
    Included after investigation : FALSE
    w3_percent                   : 11.032389
    trend_intercept              : -22.796747
    trend_slope                  : 0.052621097
    trend_p_value                : 0.20230744

  Stage: before | Procedure: MP7
    Clinical samples             : 40
    Median bias (%)              : -11.427474
    Bias SD (%)                  : 5.6481377
    Adjusted W(3) (%)            : 4.6290488
    Included after investigation : TRUE
    w3_percent                   : 12.894781
    trend_intercept              : -6.5515631
    trend_slope                  : -0.085122896
    trend_p_value                : 0.049743566

  Stage: after | Procedure: MP1
    Clinical samples             : 40
    Median bias (%)              : -0.73741264
    Bias SD (%)                  : 4.0413178
    Adjusted W(3) (%)            : 4.0413178
    Included after investigation : TRUE
    w3_percent                   : 11.18415
    trend_intercept              : -0.026587184
    trend_slope                  : 0.00031214807
    trend_p_value                : 0.99217849

  Stage: after | Procedure: MP2
    Clinical samples             : 40
    Median bias (%)              : -0.2908762
    Bias SD (%)                  : 4.9916593
    Adjusted W(3) (%)            : 4.9666072
    Included after investigation : TRUE
    w3_percent                   : 13.744843
    trend_intercept              : -1.641973
    trend_slope                  : 0.015950627
    trend_p_value                : 0.68473953

  Stage: after | Procedure: MP3
    Clinical samples             : 40
    Median bias (%)              : -0.17136128
    Bias SD (%)                  : 7.8422761
    Adjusted W(3) (%)            : 4.8633169
    Included after investigation : TRUE
    w3_percent                   : 13.458993
    trend_intercept              : 4.3152226
    trend_slope                  : -0.048689788
    trend_p_value                : 0.42878141

  Stage: after | Procedure: MP4
    Clinical samples             : 40
    Median bias (%)              : -0.28195489
    Bias SD (%)                  : 3.7935062
    Adjusted W(3) (%)            : 3.3947339
    Included after investigation : TRUE
    w3_percent                   : 9.3947606
    trend_intercept              : 0.83067063
    trend_slope                  : -0.0060932695
    trend_p_value                : 0.8384197

  Stage: after | Procedure: MP5
    Clinical samples             : 40
    Median bias (%)              : 0.3245325
    Bias SD (%)                  : 6.3376024
    Adjusted W(3) (%)            : 4.3522181
    Included after investigation : TRUE
    w3_percent                   : 12.044551
    trend_intercept              : 4.4394388
    trend_slope                  : -0.051202332
    trend_p_value                : 0.30174764

  Stage: after | Procedure: MP6
    Clinical samples             : 40
    Median bias (%)              : -21.313277
    Bias SD (%)                  : 4.8895959
    Adjusted W(3) (%)            : 3.5271045
    Included after investigation : FALSE
    w3_percent                   : 9.7610897
    trend_intercept              : -21.87256
    trend_slope                  : 0.0074119906
    trend_p_value                : 0.8473998

  Stage: after | Procedure: MP7
    Clinical samples             : 40
    Median bias (%)              : -1.0730622
    Bias SD (%)                  : 6.4531842
    Adjusted W(3) (%)            : 4.9939824
    Included after investigation : TRUE
    w3_percent                   : 13.820603
    trend_intercept              : -1.6436293
    trend_slope                  : 0.013117511
    trend_p_value                : 0.79632873
  Stage: before | Assessment set: all
    Procedures          : 7
    IMPBR (%)           : 76.599489
    Minimum procedure   : MP5
    Maximum procedure   : MP4
    Criterion (%)       : 6
    Excluded procedures : 
    Classification      : screening
    min_bias_percent    : -30.046827
    max_bias_percent    : 46.552662

  Stage: before | Assessment set: specified_exclusions
    Procedures          : 6
    IMPBR (%)           : 76.599489
    Minimum procedure   : MP5
    Maximum procedure   : MP4
    Criterion (%)       : 6
    Excluded procedures : MP6
    Classification      : screening
    min_bias_percent    : -30.046827
    max_bias_percent    : 46.552662

  Stage: after | Assessment set: all
    Procedures          : 7
    IMPBR (%)           : 21.63781
    Minimum procedure   : MP6
    Maximum procedure   : MP5
    Criterion (%)       : 6
    Excluded procedures : 
    Classification      : requires_investigation
    min_bias_percent    : -21.313277
    max_bias_percent    : 0.3245325

  Stage: after | Assessment set: specified_exclusions
    Procedures          : 6
    IMPBR (%)           : 1.3975947
    Minimum procedure   : MP7
    Maximum procedure   : MP5
    Criterion (%)       : 6
    Excluded procedures : MP6
    Classification      : commutable
    min_bias_percent    : -1.0730622
    max_bias_percent    : 0.3245325</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>IFCC Part 3：ivdtools 与官方 Table 1、2 对照</caption>
<colgroup>
<col style="width: 44%">
<col style="width: 26%">
<col style="width: 11%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">标准位置</th>
<th style="text-align: left;">统计量</th>
<th style="text-align: right;">标准结果</th>
<th style="text-align: right;">ivdtools结果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP1</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-0.40</td>
<td style="text-align: right;">-0.3891</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP1</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">4.01</td>
<td style="text-align: right;">4.0150</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP1</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">4.01</td>
<td style="text-align: right;">4.0150</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP2</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">9.50</td>
<td style="text-align: right;">9.5282</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP2</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">5.72</td>
<td style="text-align: right;">5.7223</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP2</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">5.57</td>
<td style="text-align: right;">5.5727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP3</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">20.70</td>
<td style="text-align: right;">20.6809</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP3</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">9.54</td>
<td style="text-align: right;">9.5434</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP3</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">5.90</td>
<td style="text-align: right;">5.9037</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP4</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">46.60</td>
<td style="text-align: right;">46.5527</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP4</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">6.73</td>
<td style="text-align: right;">6.7291</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP4</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">5.89</td>
<td style="text-align: right;">5.8855</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP5</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-30.00</td>
<td style="text-align: right;">-30.0468</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP5</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">4.59</td>
<td style="text-align: right;">4.5853</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP5</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">3.49</td>
<td style="text-align: right;">3.4942</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP6</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-19.40</td>
<td style="text-align: right;">-19.4472</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP6</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">5.30</td>
<td style="text-align: right;">5.2950</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP6</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">3.96</td>
<td style="text-align: right;">3.9605</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP7</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-11.40</td>
<td style="text-align: right;">-11.4275</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / before / MP7</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">5.65</td>
<td style="text-align: right;">5.6481</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / MP7</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">4.63</td>
<td style="text-align: right;">4.6290</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP1</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-0.80</td>
<td style="text-align: right;">-0.7374</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP1</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">4.05</td>
<td style="text-align: right;">4.0413</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP1</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">4.05</td>
<td style="text-align: right;">4.0413</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP2</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-0.30</td>
<td style="text-align: right;">-0.2909</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP2</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">4.99</td>
<td style="text-align: right;">4.9917</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP2</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">4.98</td>
<td style="text-align: right;">4.9666</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP3</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-0.20</td>
<td style="text-align: right;">-0.1714</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP3</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">7.83</td>
<td style="text-align: right;">7.8423</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP3</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">4.95</td>
<td style="text-align: right;">4.8633</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP4</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-0.30</td>
<td style="text-align: right;">-0.2820</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP4</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">3.80</td>
<td style="text-align: right;">3.7935</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP4</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">3.45</td>
<td style="text-align: right;">3.3947</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP5</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.3245</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP5</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">6.34</td>
<td style="text-align: right;">6.3376</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP5</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">4.39</td>
<td style="text-align: right;">4.3522</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP6</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-21.30</td>
<td style="text-align: right;">-21.3133</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP6</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">4.89</td>
<td style="text-align: right;">4.8896</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP6</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">3.57</td>
<td style="text-align: right;">3.5271</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP7</td>
<td style="text-align: left;">median_bias_percent</td>
<td style="text-align: right;">-1.10</td>
<td style="text-align: right;">-1.0731</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / MP7</td>
<td style="text-align: left;">sd_bias_percent</td>
<td style="text-align: right;">6.45</td>
<td style="text-align: right;">6.4532</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / MP7</td>
<td style="text-align: left;">adjusted_w3_percent</td>
<td style="text-align: right;">5.06</td>
<td style="text-align: right;">4.9940</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / before / ALL</td>
<td style="text-align: left;">impbr_percent</td>
<td style="text-align: right;">76.60</td>
<td style="text-align: right;">76.5995</td>
</tr>
<tr class="even">
<td style="text-align: left;">IFCC Part 3 / after / ALL</td>
<td style="text-align: left;">impbr_percent</td>
<td style="text-align: right;">21.60</td>
<td style="text-align: right;">21.6378</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IFCC Part 3 / after / EXCLUDE_MP6</td>
<td style="text-align: left;">impbr_percent</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">1.3976</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>完整程序集合的 IMPBR 从校准前约 76.6% 降至校准后约 21.6%，但仍高于 6%，所以函数返回“需要调查”，不自动判定候选参考物质对全部程序非互换，也不自动排除程序。原文进一步调查后认定候选参考物质不适合 MP6；显式设置 <code>exclude_procedures = "MP6"</code> 后，其余 6 个程序的 IMPBR 由补充资料列示值计算为约 1.4%，达到 6% 准则。</p>
<p>论文 Table 1 报告排除 MP6 后 IMPBR 为 1.5%，按公开 Table S1、S2 列示值重算约为 1.4%。论文计算所用内部未舍入结果未随补充 PDF 发布，因此不能确认该约 0.1 个百分点差异是否仅由舍入造成，表中如实保留两值。</p>
<div class="cell">
<details open="" class="code-fold">
<summary>代码</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ifcc_part3_result)</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="006-基质效应与互换性_files/figure-html/ifcc-part3-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>leave_one_out</code> 显示逐一省略程序后的敏感性结果，只用于定位调查方向。正式结论必须有校准模型、重复性和干扰调查支持；本例中的 MP6 排除是原文调查结论，不是软件根据最小 IMPBR 自动选择的结果。</p>
</section>
<section id="真实应用对照poct-葡萄糖-eqa-材料" class="level3" data-number="6.2.6">
<h3 data-number="6.2.6" class="anchored" data-anchor-id="真实应用对照poct-葡萄糖-eqa-材料"><span class="header-section-number">6.2.6</span> 真实应用对照：POCT 葡萄糖 EQA 材料</h3>
<p>Wang 等在 2020 年报告了一项真实应用研究：3 种 EQA 材料各 3 个浓度，与 33 份个体临床样品一起在 5 台 POCT 血糖仪和 1 台 Hitachi 7600 分析仪上测量。研究同时采用 CLSI EP30-A 的 Deming 回归 95% 预测区间和 IFCC 偏倚差方法；IFCC 分析在排除后使用 30 份临床样品，准则为 10%，覆盖因子为 1.9。</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>EQA 材料</th>
<th>CLSI 预测区间结果</th>
<th>IFCC 偏倚差结果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>自制人全血（HWB）</td>
<td>3 个浓度在 5/5 台 POCT 仪器上均互换</td>
<td>三个浓度分别在 3/5、4/5、3/5 台仪器上互换；有 2 台仪器三个浓度均互换</td>
</tr>
<tr class="even">
<td>商业质控物（CCM）</td>
<td>三个浓度分别在 3/5、2/5、4/5 台仪器上互换</td>
<td>在 5 台仪器上均为不确定或非互换</td>
</tr>
<tr class="odd">
<td>混合人血清（PHS）</td>
<td>三个浓度分别在 4/5、3/5、5/5 台仪器上互换</td>
<td>在 5 台仪器上均为不确定或非互换</td>
</tr>
</tbody>
</table>
<p>两条路径共同显示自制人全血优于商业质控物和混合人血清，但 IFCC 结论更保守。研究者认为，不确定结果可能与重复数或临床样品数不足、测量精密度较差以及样品特异性差异较大有关。这个案例说明：预测区间方法和偏倚差方法回答的问题及不确定度处理不同，同一材料在不同程序对、浓度和判定路径下可以得到不同分类。</p>
<p>该研究的正文没有提供足以在本章重建全部单次测量结果的数据，因此这里只进行研究设计和论文报告结果的真实应用对照，不作为 <code>ivdtools</code> 数值验证证据。来源见 <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7439342/">Wang et al., 2020, Journal of Clinical Laboratory Analysis</a>。</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "已复制");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "已复制");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./005-不确定度分析.html" class="pagination-link" aria-label="不确定度分析">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">不确定度分析</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./007-干扰研究.html" class="pagination-link" aria-label="干扰研究">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">干扰研究</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/hiox-tech/ivdtools/issues/new" class="toc-action"><i class="bi bi-github"></i>反馈问题</a></li></ul></div></div></div></footer></body></html>