<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; Linearity Analysis – ivdtools Handbook</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./015-定性分析与C5C95.html" rel="next">
<link href="./013-精密度分析.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-644e816dc738f354856c0b4d61e2aec4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/book.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./014-线性分析.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linearity Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ivdtools Handbook</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/hiox-tech/ivdtools" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./001-ivdtools包总体介绍.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">ivdtools Package Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./002-分析环境安装与使用.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Installing and Using the Analysis Environment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./003-校准曲线拟合.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Calibration Curve Fitting</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./004-稳定性研究.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Stability Studies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./005-不确定度分析.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Measurement Uncertainty Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./006-基质效应与互换性.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Matrix Effects and Commutability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./007-干扰研究.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Interference Studies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./008-稀释回收与HOOK.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Dilution Recovery, Spike Recovery, and Hook Effect</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./009-方法学比较与参考物偏倚.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Method Comparison and Reference-Material Bias</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./010-质量控制.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Quality Control</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./011-ROC曲线与cutoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">ROC Curves and Cutoff Determination</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./012-ROC曲线与多元回归.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">ROC Curves and Multivariate Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./013-精密度分析.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Precision Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./014-线性分析.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linearity Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./015-定性分析与C5C95.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Qualitative Analysis and C5/C95</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./016-检出限定量限.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Limits of Blank, Detection, and Quantitation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./017-参考区间.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Reference Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./018-瓶间差.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Bottle-to-Bottle Variation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./019-临床样本量计算.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Clinical Sample-Size Calculation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./020-异常值与正态检验.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Outlier and Normality Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./021-算法原理简介.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Introduction to Algorithm Principles</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./022-标准对应关系.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Standards Mapping</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#main-functions" id="toc-main-functions" class="nav-link active" data-scroll-target="#main-functions"><span class="header-section-number">14.1</span> Main Functions</a></li>
  <li><a href="#model-weights-and-adl" id="toc-model-weights-and-adl" class="nav-link" data-scroll-target="#model-weights-and-adl"><span class="header-section-number">14.2</span> Model, Weights, and ADL</a></li>
  <li><a href="#analysis-examples" id="toc-analysis-examples" class="nav-link" data-scroll-target="#analysis-examples"><span class="header-section-number">14.3</span> Analysis Examples</a>
  <ul>
  <li><a href="#serial-dilution-linearity" id="toc-serial-dilution-linearity" class="nav-link" data-scroll-target="#serial-dilution-linearity"><span class="header-section-number">14.3.1</span> Serial-Dilution Linearity</a></li>
  <li><a href="#polynomial-sensitivity-analysis" id="toc-polynomial-sensitivity-analysis" class="nav-link" data-scroll-target="#polynomial-sensitivity-analysis"><span class="header-section-number">14.3.2</span> Polynomial Sensitivity Analysis</a></li>
  <li><a href="#standard-cross-checks" id="toc-standard-cross-checks" class="nav-link" data-scroll-target="#standard-cross-checks"><span class="header-section-number">14.3.3</span> Standard Cross-Checks</a></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">14.4</span> Interpretation</a></li>
  <li><a href="#complete-standard-cases" id="toc-complete-standard-cases" class="nav-link" data-scroll-target="#complete-standard-cases"><span class="header-section-number">14.5</span> Complete Standard Cases</a>
  <ul>
  <li><a href="#clsi-ep06-second-edition-appendix-g-two-replicate-study" id="toc-clsi-ep06-second-edition-appendix-g-two-replicate-study" class="nav-link" data-scroll-target="#clsi-ep06-second-edition-appendix-g-two-replicate-study"><span class="header-section-number">14.5.1</span> CLSI EP06 Second Edition Appendix G: Two-Replicate Study</a></li>
  <li><a href="#clsi-ep06-second-edition-appendix-h-two-panel-study" id="toc-clsi-ep06-second-edition-appendix-h-two-panel-study" class="nav-link" data-scroll-target="#clsi-ep06-second-edition-appendix-h-two-panel-study"><span class="header-section-number">14.5.2</span> CLSI EP06 Second Edition Appendix H: Two-Panel Study</a></li>
  <li><a href="#clsi-ep06-second-edition-appendix-i-assigned-samples" id="toc-clsi-ep06-second-edition-appendix-i-assigned-samples" class="nav-link" data-scroll-target="#clsi-ep06-second-edition-appendix-i-assigned-samples"><span class="header-section-number">14.5.3</span> CLSI EP06 Second Edition Appendix I: Assigned Samples</a></li>
  <li><a href="#wst-4082024-five-level-linearity-verification" id="toc-wst-4082024-five-level-linearity-verification" class="nav-link" data-scroll-target="#wst-4082024-five-level-linearity-verification"><span class="header-section-number">14.5.4</span> WS/T 408–2024: Five-Level Linearity Verification</a></li>
  <li><a href="#yyt-1789.42022-appendix-a-linearity-sample-1" id="toc-yyt-1789.42022-appendix-a-linearity-sample-1" class="nav-link" data-scroll-target="#yyt-1789.42022-appendix-a-linearity-sample-1"><span class="header-section-number">14.5.5</span> YY/T 1789.4–2022 Appendix A: Linearity Sample 1</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/hiox-tech/ivdtools/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linearity Analysis</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Linearity evaluates whether measured results have an acceptable linear relationship with analyte concentration or target value across the working range. This chapter uses the dedicated <code>linearity()</code> workflow to summarize levels, apply weights, calculate straight-line residuals, compare allowable deviation from linearity (ADL), and perform exploratory polynomial analysis.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Scope of Use">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Scope of Use
</div>
</div>
<div class="callout-body-container callout-body">
<p>The core of CLSI EP06, 2nd edition, is comparison of straight-line residuals with a prespecified ADL. A high correlation or a nonsignificant quadratic term alone does not establish linearity. <code>method="polynomial"</code> reproduces the superseded EP6-A approach and should be labeled exploratory. The functions do not replace professional judgment about sample preparation, commutability, endpoint coverage, interference, or the reporting range.</p>
</div>
</div>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["Design LOW/HIGH and dilution levels"] --&gt; B["linearity_replicates()&lt;br/&gt;linearity_panel()"]
    B --&gt; C["Replicate long table"]
    C --&gt; D["linearity()&lt;br/&gt;Aggregate and fit"]
    D --&gt; E["Residuals, intervals, ADL"]
    E --&gt; F["linearity_endpoints()&lt;br/&gt;Check endpoints"]
    F --&gt; G["Claim linearity only within&lt;br/&gt;the validated range"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ivdtools)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="main-functions" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="main-functions"><span class="header-section-number">14.1</span> Main Functions</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Main purpose</th>
<th>Key input or output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>linearity_replicates()</code></td>
<td>Calculate replicates per level from precision and ADL</td>
<td><code>imprecision</code>, <code>adl</code>, <code>family_error</code></td>
</tr>
<tr class="even">
<td><code>linearity_panel()</code></td>
<td>Design a HIGH/LOW preparation series</td>
<td><code>proportion_high</code>, <code>high</code>, <code>low</code>, <code>total_volume</code></td>
</tr>
<tr class="odd">
<td><code>linearity_endpoints()</code></td>
<td>Calculate laboratory-confirmed LOW/HIGH targets</td>
<td>LLoQ/ULoQ and low/high-end CV</td>
</tr>
<tr class="even">
<td><code>linearity()</code></td>
<td>EP06 parameterized linearity analysis</td>
<td><code>method</code>, <code>weights</code>, <code>conf.level</code>, <code>adl_*</code></td>
</tr>
<tr class="odd">
<td><code>plot()</code></td>
<td>Plot fit, residuals, precision, or model differences</td>
<td><code>type</code></td>
</tr>
</tbody>
</table>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearity_replicates</span>(<span class="at">imprecision =</span> <span class="dv">4</span>, <span class="at">adl =</span> <span class="dv">5</span>, <span class="at">levels =</span> <span class="dv">8</span>, <span class="at">family_error =</span> <span class="fl">0.10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Type: relative
    Imprecision           : 4
    ADL                   : 5
    True deviation        : 0
    Effective ADL         : 5
    Level probability     : 0.98691628
    Z                     : 2.4814824
    Calculated replicates : 3.940963
    Replicates            : 4
    Recommend four        : FALSE</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearity_panel</span>(<span class="at">proportion_high =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">6</span>), <span class="at">high =</span> <span class="dv">1000</span>, <span class="at">low =</span> <span class="dv">10</span>, <span class="at">total_volume =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Sample: S1
    Proportion high        : 0
    Proportion low         : 1
    Expected               : 10
    Relative concentration : 0.01
    Total volume           : 1
    High volume            : 0
    Low volume             : 1

  Sample: S2
    Proportion high        : 0.2
    Proportion low         : 0.8
    Expected               : 208
    Relative concentration : 0.208
    Total volume           : 1
    High volume            : 0.2
    Low volume             : 0.8

  Sample: S3
    Proportion high        : 0.4
    Proportion low         : 0.6
    Expected               : 406
    Relative concentration : 0.406
    Total volume           : 1
    High volume            : 0.4
    Low volume             : 0.6

  Sample: S4
    Proportion high        : 0.6
    Proportion low         : 0.4
    Expected               : 604
    Relative concentration : 0.604
    Total volume           : 1
    High volume            : 0.6
    Low volume             : 0.4

  Sample: S5
    Proportion high        : 0.8
    Proportion low         : 0.2
    Expected               : 802
    Relative concentration : 0.802
    Total volume           : 1
    High volume            : 0.8
    Low volume             : 0.2

  Sample: S6
    Proportion high        : 1
    Proportion low         : 0
    Expected               : 1000
    Relative concentration : 1
    Total volume           : 1
    High volume            : 1
    Low volume             : 0</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearity_endpoints</span>(<span class="at">lloq =</span> <span class="dv">10</span>, <span class="at">uloq =</span> <span class="dv">1000</span>, <span class="at">cv_high =</span> <span class="dv">5</span>, <span class="at">cv_at_lloq =</span> <span class="dv">20</span>, <span class="at">cv_at_k_lloq =</span> <span class="dv">15</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>CLSI EP06-Ed2 target concentrations
  LOW target: 14.14116
  HIGH target: 924.0072</code></pre>
</div>
</div>
<p>The replicate-count function reports a design quantity only. Final level and replicate counts must satisfy the protocol, applicable standard, and available samples. LOW/HIGH calculations use laboratory-confirmed target concentrations and are not a substitute for a manufacturer’s validation process.</p>
</section>
<section id="model-weights-and-adl" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="model-weights-and-adl"><span class="header-section-number">14.2</span> Model, Weights, and ADL</h2>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearity_replicates</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  imprecision, adl, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"relative"</span>, <span class="st">"absolute"</span>),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">level_probability =</span> <span class="fl">0.99</span>, <span class="at">levels =</span> <span class="cn">NULL</span>, <span class="at">family_error =</span> <span class="cn">NULL</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">true_deviation =</span> <span class="dv">0</span>, <span class="at">min_replicates =</span> <span class="dv">2</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">linearity_panel</span>(proportion_high, high, <span class="at">low =</span> <span class="dv">0</span>, <span class="at">total_volume =</span> <span class="cn">NULL</span>, <span class="at">sample =</span> <span class="cn">NULL</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">linearity</span>(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  data, sample, result, x, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"linear"</span>, <span class="st">"polynomial"</span>),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">intercept =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="fu">c</span>(<span class="st">"equal"</span>, <span class="st">"level_variance"</span>, <span class="st">"pooled"</span>, <span class="st">"precision_profile"</span>),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">variance_group =</span> <span class="cn">NULL</span>, <span class="at">conf.level =</span> <span class="cn">NULL</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">multiplicity =</span> <span class="fu">c</span>(<span class="st">"familywise"</span>, <span class="st">"none"</span>), <span class="at">adl =</span> <span class="cn">NULL</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">adl_abs =</span> <span class="cn">NULL</span>, <span class="at">adl_rel =</span> <span class="cn">NULL</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>If the per-level central coverage is <span class="math inline">\(P_L\)</span>, repeatability is <span class="math inline">\(s\)</span>, expected true deviation is <span class="math inline">\(δ_0\)</span>, and effective ADL is <span class="math inline">\(A_{\mathrm{eff}}=A-δ_0\)</span>, the replicate count is</p>
<p><span class="math display">\[n=\left\lceil\left(\frac{z_{(1+P_L)/2}s}{A_{\mathrm{eff}}}\right)^2\right\rceil.\]</span></p>
<p>For familywise error <span class="math inline">\(α_F\)</span> over <span class="math inline">\(L\)</span> levels, <span class="math inline">\(P_L=(1-α_F)^{1/L}\)</span>. Relative inputs use percentage units: 5 means 5%.</p>
<p>With high-sample proportion <span class="math inline">\(p_h\)</span>,</p>
<p><span class="math display">\[x_{\mathrm{expected}}=p_hx_H+(1-p_h)x_L.\]</span></p>
<p><code>linearity(method="linear")</code> first summarizes each level as <span class="math inline">\(\bar y_j,s_j,n_j\)</span> and fits <span class="math inline">\(\bar y_j=\beta_0+\beta_1x_j+e_j\)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><code>weights</code></th>
<th>Level-mean weight</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>equal</code></td>
<td><span class="math inline">\(1\)</span></td>
<td>Equal weight</td>
</tr>
<tr class="even">
<td><code>level_variance</code></td>
<td><span class="math inline">\(n_j/s_j^2\)</span></td>
<td>Use the variance at each level</td>
</tr>
<tr class="odd">
<td><code>pooled</code></td>
<td><span class="math inline">\(n_j/\widehat\sigma_g^2\)</span></td>
<td>Use groups supplied in <code>variance_group</code>; no automatic grouping</td>
</tr>
<tr class="even">
<td><code>precision_profile</code></td>
<td><span class="math inline">\(1/\widehat\sigma_j^2\)</span></td>
<td>Use variance predicted from an SD–mean profile</td>
</tr>
</tbody>
</table>
<p>The residual is <span class="math inline">\(r_j=\bar y_j-\widehat y_j\)</span>, and ADL is exceeded when <span class="math inline">\(|r_j|&gt;ADL_j\)</span>. When <code>weights="pooled"</code>, groups must be explicit, contiguous after sorting by <span class="math inline">\(x\)</span>, and contain at least two levels. <code>percent_base</code> determines the denominator of relative residuals. <code>multiplicity="familywise"</code> converts overall coverage to per-level coverage; <code>"none"</code> uses the overall coverage at every level.</p>
</section>
<section id="analysis-examples" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="analysis-examples"><span class="header-section-number">14.3</span> Analysis Examples</h2>
<section id="serial-dilution-linearity" class="level3" data-number="14.3.1">
<h3 data-number="14.3.1" class="anchored" data-anchor-id="serial-dilution-linearity"><span class="header-section-number">14.3.1</span> Serial-Dilution Linearity</h3>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dilution <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"./data/014-线性分析/linearity-dilution.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>dilution <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(dilution)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dilution, <span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  conc replicate signal
1   50         1   48.6
2   50         2   49.2
3   50         3   50.0
4  100         1  101.3
5  100         2   99.7
6  100         3  101.4</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fit_lin <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  dilution, <span class="at">sample =</span> <span class="st">"conc"</span>, <span class="at">result =</span> <span class="st">"signal"</span>, <span class="at">x =</span> <span class="st">"conc"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"linear"</span>, <span class="at">weights =</span> <span class="st">"equal"</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">multiplicity =</span> <span class="st">"familywise"</span>, <span class="at">adl_rel =</span> <span class="dv">5</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fit_lin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linearity regression analysis

Analysis settings

Method: linear (EP06-Ed2)
Observations / levels: 24 / 8
Intercept: estimated
Weights: equal
Fit unit: level_mean

Model comparison

Degree: 1
Observations                : 8
Parameters                  : 2
Residual degrees of freedom : 6
RSS                         : 146.65863
Weighted RSS                : 146.65863
SY.X                        : 4.9439969
Weighted SY.X               : 4.9439969
R-squared                   : 0.99999571
Adjusted R-squared          : 0.999995

Regression coefficients

     Estimate  Std. Error    t value Pr(&gt;|t|)    
a 0.975290473 2.205878722    0.44213  0.67388    
b 0.998893935 0.000844269 1183.14720  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample fit information

Sample  Expected  Predicted  Observed mean  Weight  Observed SD  n
50            50     50.920        49.2667       1     0.702377  3
100          100    100.865       100.8000       1     0.953939  3
200          200    200.754       202.6667       1     4.452340  3
400          400    400.533       397.8333       1     7.396170  3
800          800    800.090       798.8667       1    10.261741  3
1600        1600   1599.206      1596.9000       1    13.753545  3
3200        3200   3197.436      3207.8000       1    20.940869  3
6400        6400   6393.896      6389.5667       1    19.923437  3

Sample bias information

Sample   Residual  Recovery bias  Residual (%)  Recovery bias (%)        ADL  Decision  
50      -1.653321      -0.733333    -3.2468990          -1.466667    2.54600  Within ADL
100     -0.064684       0.800000    -0.0641295           0.800000    5.04323  Within ADL
200      1.912589       2.666667     0.9527025           1.333333   10.03770  Within ADL
400     -2.699531      -2.166667    -0.6739850          -0.541667   20.02664  Within ADL
800     -1.223772      -1.133333    -0.1529542          -0.141667   40.00452  Within ADL
1600    -2.305587      -3.100000    -0.1441708          -0.193750   79.96028  Within ADL
3200    10.364116       7.800000     0.3241384           0.243750  159.87179  Within ADL
6400    -4.329810     -10.433333    -0.0677179          -0.163021  319.69482  Within ADL

Definitions

Residual = observed mean - predicted value.
Recovery bias = observed mean - expected value.
Recovery bias (%) = 100 * recovery bias / expected value.
Residual (%) denominator: predicted.
ADL decision metric = residual.</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_lin, <span class="at">type =</span> <span class="st">"fit"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="014-线性分析_files/figure-html/fit-linear-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_lin, <span class="at">type =</span> <span class="st">"residual"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="014-线性分析_files/figure-html/fit-linear-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>adl_exceeded</code> is a numeric comparison with the ADL supplied by the caller, not a complete product-acceptance decision. Choose weights according to the design and heteroscedasticity structure, and compare residuals, back-calculated bias, and prespecified criteria.</p>
</section>
<section id="polynomial-sensitivity-analysis" class="level3" data-number="14.3.2">
<h3 data-number="14.3.2" class="anchored" data-anchor-id="polynomial-sensitivity-analysis"><span class="header-section-number">14.3.2</span> Polynomial Sensitivity Analysis</h3>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>poly_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"./data/014-线性分析/linearity-polynomial.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>poly_data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(poly_data)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(poly_data, <span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    conc replicate signal
1  75.00         1   75.0
2  75.00         2   75.0
3  75.00         3   74.4
4 483.75         1  454.1
5 483.75         2  455.3
6 483.75         3  456.0</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fit_poly <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  poly_data, <span class="at">sample =</span> <span class="st">"conc"</span>, <span class="at">result =</span> <span class="st">"signal"</span>, <span class="at">x =</span> <span class="st">"conc"</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"polynomial"</span>, <span class="at">weights =</span> <span class="st">"level_variance"</span>, <span class="at">max_degree =</span> <span class="dv">3</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">poly_alpha =</span> <span class="fl">0.05</span>, <span class="at">percent_base =</span> <span class="st">"predicted"</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fit_poly)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linearity regression analysis

Analysis settings

Method: polynomial (EP6-A, exploratory)
Observations / levels: 15 / 5
Intercept: estimated
Weights: level_variance
Fit unit: observation
Selected degree: 3

Model comparison

Degree: 1
Observations                : 15
Parameters                  : 2
Residual degrees of freedom : 13
RSS                         : 52631.917
Weighted RSS                : 550.93015
SY.X                        : 63.62868
Weighted SY.X               : 6.5099341
R-squared                   : 0.99902344
Adjusted R-squared          : 0.99894832

Degree: 2
Observations                : 15
Parameters                  : 3
Residual degrees of freedom : 12
RSS                         : 10241.163
Weighted RSS                : 30.175825
SY.X                        : 29.213529
Weighted SY.X               : 1.5857655
R-squared                   : 0.99994651
Adjusted R-squared          : 0.9999376

Degree: 3
Observations                : 15
Parameters                  : 4
Residual degrees of freedom : 11
RSS                         : 4360.5146
Weighted RSS                : 15.881083
SY.X                        : 19.910058
Weighted SY.X               : 1.2015552
R-squared                   : 0.99997185
Adjusted R-squared          : 0.99996417
Selected                    : Yes

Regression coefficients (degree 1)

    Estimate Std. Error   t value Pr(&gt;|t|)    
a 3.26682147 1.60149874   2.03985 0.062224 .  
b 0.94635339 0.00820623 115.32135  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Regression coefficients (degree 2)

     Estimate  Std. Error  t value   Pr(&gt;|t|)    
a 7.07723e+00 4.71485e-01  15.0105 3.8555e-09 ***
b 8.98365e-01 3.88796e-03 231.0636 &lt; 2.22e-16 ***
c 5.87581e-05 4.08310e-06  14.3905 6.2393e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Regression coefficients (degree 3, selected)

      Estimate   Std. Error  t value   Pr(&gt;|t|)    
a  1.08167e+01  1.24094e+00  8.71655 2.8637e-06 ***
b  8.38991e-01  1.90976e-02 43.93179 1.0374e-13 ***
c  1.93013e-04  4.27784e-05  4.51193  0.0008837 ***
d -5.97186e-08  1.89786e-08 -3.14662  0.0092980 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample fit information

Sample   Expected  Predicted  Observed mean      Weight  Observed SD  n
75          75.00    74.8015         74.800  8.33333333     0.346410  3
483.75     483.75   455.0861        455.133  1.08303249     0.960902  3
892.5      892.50   870.9067        865.967  0.01552474     8.025792  3
1301.25   1301.25  1297.7933       1328.467  0.00166688    24.493332  3
1710      1710.00  1711.2760       1710.433  0.01516914     8.119319  3

Sample bias information

Sample      Residual  Recovery bias  Residual (%)  Recovery bias (%)         DL  ADL  Decision    
75       -0.00153386      -0.200000   -0.00206599         -0.2666667   0.558208   NA  Not assessed
483.75    0.04720887     -28.616667    0.01023909         -5.9155900  -5.979149   NA  Not assessed
892.5    -4.94005897     -26.533333   -0.58263161         -2.9729225  23.019504   NA  Not assessed
1301.25  30.67332481      27.216667    2.48425504          2.0915786  63.084173   NA  Not assessed
1710     -0.84264426       0.433333   -0.05196596          0.0253411  89.744861   NA  Not assessed

Definitions

Residual = observed mean - predicted value.
Recovery bias = observed mean - expected value.
Recovery bias (%) = 100 * recovery bias / expected value.
Residual (%) denominator: predicted.
ADL decision metric = deviation from linearity (DL).

Warnings / interpretation notes

1 duplicate sample/result/x row(s) were retained.

Polynomial regression follows superseded EP6-A and is exploratory under EP06-Ed2. </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_poly, <span class="at">type =</span> <span class="st">"fit"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="014-线性分析_files/figure-html/fit-polynomial-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_poly, <span class="at">type =</span> <span class="st">"difference"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="014-线性分析_files/figure-html/fit-polynomial-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="standard-cross-checks" class="level3" data-number="14.3.3">
<h3 data-number="14.3.3" class="anchored" data-anchor-id="standard-cross-checks"><span class="header-section-number">14.3.3</span> Standard Cross-Checks</h3>
<p>The package can reproduce the principal calculations in CLSI EP06 Appendices G–I and the YY/T 1789.4 Appendix A.5 linearity example using the supplied CSV files. The following pattern illustrates the EP06 Appendix G weighting and the reporting convention:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>ep06_g <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">read_csv</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/014-线性分析/std-ep06-appendix-g.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>ep06_g_ivd <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  ep06_g, <span class="at">sample =</span> <span class="st">"level"</span>, <span class="at">result =</span> <span class="st">"result"</span>, <span class="at">x =</span> <span class="st">"expected"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"linear"</span>, <span class="at">intercept =</span> <span class="cn">FALSE</span>, <span class="at">weights =</span> <span class="st">"pooled"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">variance_group =</span> <span class="st">"variance_group"</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>ep06_g_ivd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linearity regression analysis

Analysis settings

Method: linear (EP06-Ed2)
Observations / levels: 20 / 10
Intercept: fixed at zero
Weights: pooled
Variance group: variance_group
Fit unit: level_mean

Model comparison

Degree: 1
Observations                : 10
Parameters                  : 1
Residual degrees of freedom : 9
RSS                         : 2010.7972
Weighted RSS                : 83.183953
SY.X                        : 14.947304
Weighted SY.X               : 3.0401746
R-squared                   : 0.99911786
Adjusted R-squared          : 0.99901984

Regression coefficients

   Estimate Std. Error t value   Pr(&gt;|t|)    
b 1.0677279  0.0105755 100.962 4.6544e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Pooled variance groups

Variance group: low
Levels             : 3
Degrees of freedom : 3
Minimum x          : 52.9
Maximum x          : 158.7
Pooled variance    : 1.21
Pooled SD          : 1.1
Level-mean weight  : 1.6528926
Minimum weight     : 1.6528926
Maximum weight     : 1.6528926

Variance group: middle
Levels             : 4
Degrees of freedom : 4
Minimum x          : 211.6
Maximum x          : 370.3
Pooled variance    : 55.255
Pooled SD          : 7.4333707
Level-mean weight  : 0.036195819
Minimum weight     : 0.036195819
Maximum weight     : 0.036195819

Variance group: high
Levels             : 3
Degrees of freedom : 3
Minimum x          : 423.2
Maximum x          : 529
Pooled variance    : 267.72167
Pooled SD          : 16.362202
Level-mean weight  : 0.0074704451
Minimum weight     : 0.0074704451
Maximum weight     : 0.0074704451

Sample fit information

Sample  Expected  Predicted  Observed mean      Weight  Observed SD  n
10          52.9    56.4828          51.25  1.65289256     0.353553  2
9          105.8   112.9656         111.30  1.65289256     1.838478  2
8          158.7   169.4484         171.95  1.65289256     0.353553  2
7          211.6   225.9312         233.15  0.03619582     5.586144  2
6          264.5   282.4140         292.05  0.03619582     6.293250  2
5          317.4   338.8968         350.15  0.03619582     4.879037  2
4          370.3   395.3796         391.45  0.03619582    11.242998  2
3          423.2   451.8624         468.20  0.00747045    20.364675  2
2          476.1   508.3453         496.65  0.00747045    18.879751  2
1          529.0   564.8281         529.00  0.00747045     5.656854  2

Sample bias information

Sample   Residual  Recovery bias  Residual (%)  Recovery bias (%)  ADL  Decision    
10       -5.23281          -1.65      -9.26442           -3.11909   NA  Not assessed
9        -1.66561           5.50      -1.47444            5.19849   NA  Not assessed
8         2.50158          13.25       1.47631            8.34909   NA  Not assessed
7         7.21878          21.55       3.19512           10.18431   NA  Not assessed
6         9.63597          27.55       3.41200           10.41588   NA  Not assessed
5        11.25317          32.75       3.32053           10.31821   NA  Not assessed
4        -3.92964          21.15      -0.99389            5.71159   NA  Not assessed
3        16.33755          45.00       3.61560           10.63327   NA  Not assessed
2       -11.69525          20.55      -2.30065            4.31632   NA  Not assessed
1       -35.82806           0.00      -6.34318            0.00000   NA  Not assessed

Definitions

Residual = observed mean - predicted value.
Recovery bias = observed mean - expected value.
Recovery bias (%) = 100 * recovery bias / expected value.
Residual (%) denominator: predicted.
ADL decision metric = residual.</code></pre>
</div>
</div>
<p>The ten levels are explicitly grouped as 1–3, 4–7, and 8–10. The user supplies these groups from the repeatability-SD–concentration assessment and protocol; the function does not select a favorable grouping.</p>
<p>For Appendix H, use <code>weights = "level_variance"</code> and fit the combined panel and each panel separately. For Appendix I, use the published summary data and weights <span class="math inline">\(10/s^2\)</span> rather than manufacturing pseudo-raw replicates. The standard’s higher-order model-selection and ADL-PctBnd lookup are not identical to the package’s exploratory polynomial mode; report this algorithm difference explicitly.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>yyt1789_4 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"./data/014-线性分析/std-ep06-appendix-g.csv"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>yyt1789_4_fit <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  yyt1789_4, <span class="at">sample =</span> <span class="st">"level"</span>, <span class="at">result =</span> <span class="st">"result"</span>, <span class="at">x =</span> <span class="st">"expected"</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"linear"</span>, <span class="at">weights =</span> <span class="st">"equal"</span>, <span class="at">adl_rel =</span> <span class="dv">10</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>yyt1789_4_fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linearity regression analysis

Analysis settings

Method: linear (EP06-Ed2)
Observations / levels: 20 / 10
Intercept: estimated
Weights: equal
Fit unit: level_mean

Model comparison

Degree: 1
Observations                : 10
Parameters                  : 2
Residual degrees of freedom : 8
RSS                         : 1709.9271
Weighted RSS                : 1709.9271
SY.X                        : 14.61988
Weighted SY.X               : 14.61988
R-squared                   : 0.99309927
Adjusted R-squared          : 0.99223668

Regression coefficients

   Estimate Std. Error t value   Pr(&gt;|t|)    
a 9.1333333  9.9872792  0.9145    0.38719    
b 1.0324168  0.0304271 33.9308 6.2178e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample fit information

Sample  Expected  Predicted  Observed mean  Weight  Observed SD  n
10          52.9    63.7482          51.25       1     0.353553  2
9          105.8   118.3630         111.30       1     1.838478  2
8          158.7   172.9779         171.95       1     0.353553  2
7          211.6   227.5927         233.15       1     5.586144  2
6          264.5   282.2076         292.05       1     6.293250  2
5          317.4   336.8224         350.15       1     4.879037  2
4          370.3   391.4373         391.45       1    11.242998  2
3          423.2   446.0521         468.20       1    20.364675  2
2          476.1   500.6670         496.65       1    18.879751  2
1          529.0   555.2818         529.00       1     5.656854  2

Sample bias information

Sample     Residual  Recovery bias  Residual (%)  Recovery bias (%)       ADL  Decision   
10      -12.4981818          -1.65  -19.60555025           -3.11909   6.37482  Exceeds ADL
9        -7.0630303           5.50   -5.96726046            5.19849  11.83630  Within ADL 
8        -1.0278788          13.25   -0.59422557            8.34909  17.29779  Within ADL 
7         5.5572727          21.55    2.44176200           10.18431  22.75927  Within ADL 
6         9.8424242          27.55    3.48765416           10.41588  28.22076  Within ADL 
5        13.3275758          32.75    3.95685524           10.31821  33.68224  Within ADL 
4         0.0127273          21.15    0.00325142            5.71159  39.14373  Within ADL 
3        22.1478788          45.00    4.96531184           10.63327  44.60521  Within ADL 
2        -4.0169697          20.55   -0.80232369            4.31632  50.06670  Within ADL 
1       -26.2818182           0.00   -4.73305938            0.00000  55.52818  Within ADL 

Definitions

Residual = observed mean - predicted value.
Recovery bias = observed mean - expected value.
Recovery bias (%) = 100 * recovery bias / expected value.
Residual (%) denominator: predicted.
ADL decision metric = residual.</code></pre>
</div>
</div>
</section>
</section>
<section id="interpretation" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">14.4</span> Interpretation</h2>
<ol type="1">
<li>A successful fit does not establish model suitability; evaluate residuals, bias, acceptance limits, and the protocol.</li>
<li>Examine residuals on both original and relative scales, especially when values span orders of magnitude.</li>
<li>Select weights using the observed variance structure or protocol requirements.</li>
<li>Conclusions apply only within the validated range; avoid unsupported extrapolation.</li>
<li>Preserve raw data, code, model parameters, convergence information, package version, and session information.</li>
</ol>
</section>
<section id="complete-standard-cases" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="complete-standard-cases"><span class="header-section-number">14.5</span> Complete Standard Cases</h2>
<section id="clsi-ep06-second-edition-appendix-g-two-replicate-study" class="level3" data-number="14.5.1">
<h3 data-number="14.5.1" class="anchored" data-anchor-id="clsi-ep06-second-edition-appendix-g-two-replicate-study"><span class="header-section-number">14.5.1</span> CLSI EP06 Second Edition Appendix G: Two-Replicate Study</h3>
<p>Appendix G prepares ten levels by mixing HIGH with blank at relative concentrations of 0.1–1.0, with two measurements per level. The prespecified linear interval is 55–500 U/L and the allowable deviation from linearity is ±10%. Because there are only two replicates per level, the standard pools adjacent-level variances into three groups and uses <span class="math inline">\(2/\overline{s^2}\)</span> as the no-intercept WLS weight. The grouping column is written directly into the CSV according to standard Table G3, and expected values are already calculated from the HIGH concentration and preparation proportions.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ep06_g <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">read_csv</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/014-线性分析/std-ep06-appendix-g.csv"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>ep06_g_ivd <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  ep06_g, <span class="at">sample =</span> <span class="st">"level"</span>, <span class="at">result =</span> <span class="st">"result"</span>, <span class="at">x =</span> <span class="st">"expected"</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"linear"</span>, <span class="at">intercept =</span> <span class="cn">FALSE</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="st">"pooled"</span>, <span class="at">variance_group =</span> <span class="st">"variance_group"</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>EP06 Second Edition Appendix G: ivdtools compared with the standard text</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Standard location</th>
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Standard</th>
<th style="text-align: right;">ivdtools</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EP06 Ed2 Appendix G</td>
<td style="text-align: left;">WLS_slope</td>
<td style="text-align: right;">1.0677</td>
<td style="text-align: right;">1.0677</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP06 Ed2 Appendix G</td>
<td style="text-align: left;">max_abs_deviation_percent</td>
<td style="text-align: right;">9.3000</td>
<td style="text-align: right;">9.2644</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>variance_group explicitly assigns levels 1–3, 4–7, and 8–10 to three groups. The grouping is supplied by the analyst from the repeatability-SD versus concentration plot and the prespecified plan; the function does not select the most favorable grouping automatically.</p>
</section>
<section id="clsi-ep06-second-edition-appendix-h-two-panel-study" class="level3" data-number="14.5.2">
<h3 data-number="14.5.2" class="anchored" data-anchor-id="clsi-ep06-second-edition-appendix-h-two-panel-study"><span class="header-section-number">14.5.2</span> CLSI EP06 Second Edition Appendix H: Two-Panel Study</h3>
<p>Appendix H prepares two panels, HIGH1 and HIGH2, separately with blank, at ten levels per panel and five measurements per level, for 100 results. HIGH1 covers the high end and HIGH2 the low end; together they cover the case’s prespecified 20–1,000 U/L range. Each level receives weight <span class="math inline">\(5/s^2\)</span> in a no-intercept WLS fit. The CSV includes sample_id and expected values determined by panel, level, and preparation proportion, so it can enter the analysis directly.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>ep06_h <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">read_csv</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/014-线性分析/std-ep06-appendix-h.csv"</span>,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>ep06_h_fit <span class="ot">&lt;-</span> <span class="cf">function</span>(z) {</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    z, <span class="at">sample =</span> <span class="st">"sample_id"</span>, <span class="at">result =</span> <span class="st">"result"</span>, <span class="at">x =</span> <span class="st">"expected"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"linear"</span>, <span class="at">intercept =</span> <span class="cn">FALSE</span>, <span class="at">weights =</span> <span class="st">"level_variance"</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">slope =</span> fit<span class="sc">$</span>coefficients<span class="sc">$</span>estimate,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_abs_deviation_percent =</span> <span class="fu">max</span>(<span class="fu">abs</span>(fit<span class="sc">$</span>level_summary<span class="sc">$</span>percent_residual_linear))</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>ep06_h_combined <span class="ot">&lt;-</span> <span class="fu">ep06_h_fit</span>(ep06_h)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>ep06_h_separate <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">split</span>(ep06_h, ep06_h<span class="sc">$</span>panel), ep06_h_fit</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>EP06 Second Edition Appendix H: ivdtools compared with the standard text</caption>
<colgroup>
<col style="width: 28%">
<col style="width: 44%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Standard location</th>
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Standard</th>
<th style="text-align: right;">ivdtools</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EP06 Ed2 Appendix H</td>
<td style="text-align: left;">combined WLS slope</td>
<td style="text-align: right;">0.9686</td>
<td style="text-align: right;">0.9686</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP06 Ed2 Appendix H</td>
<td style="text-align: left;">combined maximum deviation (%)</td>
<td style="text-align: right;">14.5000</td>
<td style="text-align: right;">14.4759</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP06 Ed2 Appendix H</td>
<td style="text-align: left;">HIGH1 WLS slope</td>
<td style="text-align: right;">0.9496</td>
<td style="text-align: right;">0.9496</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP06 Ed2 Appendix H</td>
<td style="text-align: left;">HIGH1 maximum deviation (%)</td>
<td style="text-align: right;">12.8000</td>
<td style="text-align: right;">12.7612</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EP06 Ed2 Appendix H</td>
<td style="text-align: left;">HIGH2 WLS slope</td>
<td style="text-align: right;">1.0013</td>
<td style="text-align: right;">1.0013</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP06 Ed2 Appendix H</td>
<td style="text-align: left;">HIGH2 maximum deviation (%)</td>
<td style="text-align: right;">9.2000</td>
<td style="text-align: right;">9.2134</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The maximum deviation in all three analyses is below the case’s prespecified ±15%, but the overlap, range coverage, and weighting structure of the two panels are prerequisites for that conclusion.</p>
</section>
<section id="clsi-ep06-second-edition-appendix-i-assigned-samples" class="level3" data-number="14.5.3">
<h3 data-number="14.5.3" class="anchored" data-anchor-id="clsi-ep06-second-edition-appendix-i-assigned-samples"><span class="header-section-number">14.5.3</span> CLSI EP06 Second Edition Appendix I: Assigned Samples</h3>
<p>Appendix I provides true values, ten-measurement means, and SDs for nine spiked samples but does not publish the 90 individual measurements. This case therefore retains the published summary granularity and does not create pseudo-raw observations from the means and SDs. The weight is <span class="math inline">\(10/s^2\)</span>, the fitted model is a no-intercept WLS line, and the prespecified allowable deviation is ±2%.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>ep06_i <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">read_csv</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/014-线性分析/std-ep06-appendix-i-summary.csv"</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>ep06_i<span class="sc">$</span>weight <span class="ot">&lt;-</span> ep06_i<span class="sc">$</span>n <span class="sc">/</span> ep06_i<span class="sc">$</span>sd<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>ep06_i_ivd <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  ep06_i, <span class="at">sample =</span> <span class="st">"sample"</span>, <span class="at">result =</span> <span class="st">"measured_mean"</span>, <span class="at">x =</span> <span class="st">"true_value"</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"linear"</span>, <span class="at">intercept =</span> <span class="cn">FALSE</span>, <span class="at">weights =</span> ep06_i<span class="sc">$</span>weight</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>EP06 Second Edition Appendix I: ivdtools compared with the standard text</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Standard location</th>
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Standard</th>
<th style="text-align: right;">ivdtools</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EP06 Ed2 Appendix I</td>
<td style="text-align: left;">WLS_slope</td>
<td style="text-align: right;">1.0045</td>
<td style="text-align: right;">1.0045</td>
</tr>
<tr class="even">
<td style="text-align: left;">EP06 Ed2 Appendix I</td>
<td style="text-align: left;">max_abs_deviation_percent</td>
<td style="text-align: right;">1.7000</td>
<td style="text-align: right;">1.7212</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The recalculated maximum absolute deviation is within the case’s prespecified ±2%. Recovery bias and linearity deviation answer different questions: the former is relative to the true value, while the latter is relative to the best-fit line, so they cannot replace one another.</p>
</section>
<section id="wst-4082024-five-level-linearity-verification" class="level3" data-number="14.5.4">
<h3 data-number="14.5.4" class="anchored" data-anchor-id="wst-4082024-five-level-linearity-verification"><span class="header-section-number">14.5.4</span> WS/T 408–2024: Five-Level Linearity Verification</h3>
<p>The HDL-C case in Appendix A.4 contains five levels with three measurements per level. The standard focuses on the residual SD of the straight-line regression, <span class="math inline">\(s_{y|x}\)</span>, the within-run SD <span class="math inline">\(s_{WR}\)</span>, their F ratio, and the nonlinear SD <span class="math inline">\(s_{NL}\)</span>.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>wst408_linearity <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/014-线性分析/std-wst408-linearity.csv"</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>wst408_linearity_ivd <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(wst408_linearity), <span class="at">sample =</span> <span class="st">"level"</span>, <span class="at">result =</span> <span class="st">"measured"</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="st">"expected"</span>, <span class="at">method =</span> <span class="st">"linear"</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>WS/T 408 Appendix A.4: ivdtools compared with the standard text</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Standard location</th>
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Standard</th>
<th style="text-align: right;">ivdtools</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">WS/T 408 Appendix A.4</td>
<td style="text-align: left;">s_yx</td>
<td style="text-align: right;">0.0318</td>
<td style="text-align: right;">0.03277</td>
</tr>
<tr class="even">
<td style="text-align: left;">WS/T 408 Appendix A.4</td>
<td style="text-align: left;">s_WR</td>
<td style="text-align: right;">0.0186</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WS/T 408 Appendix A.4</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">2.9130</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">WS/T 408 Appendix A.4</td>
<td style="text-align: left;">s_NL</td>
<td style="text-align: right;">0.0258</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>linearity() fits the line to the five level means and returns <span class="math inline">\(s_{y|x}\approx0.0328\)</span>; the standard companion table gives 0.0318. The s_WR, F, and s_NL quantities required by the standard are not public results in the current object, so the table marks them explicitly as NA.</p>
</section>
<section id="yyt-1789.42022-appendix-a-linearity-sample-1" class="level3" data-number="14.5.5">
<h3 data-number="14.5.5" class="anchored" data-anchor-id="yyt-1789.42022-appendix-a-linearity-sample-1"><span class="header-section-number">14.5.5</span> YY/T 1789.4–2022 Appendix A: Linearity Sample 1</h3>
<p>Appendix A.5 provides 14 dilution levels for AFP linearity sample 1, with four results per level. The standard selects a model using significance of higher-order polynomial terms and then evaluates level-specific relative bias from the final line against a ±10% allowable error.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>yyt1789_4 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"./data/014-线性分析/std-yyt1789-4-appendix-a-sample1.csv"</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>yyt1789_4_linear_p <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  yyt1789_4, <span class="at">sample =</span> <span class="st">"level"</span>, <span class="at">result =</span> <span class="st">"result"</span>, <span class="at">x =</span> <span class="st">"dilution"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"polynomial"</span>, <span class="at">weights =</span> <span class="st">"equal"</span>, <span class="at">adl_rel =</span> <span class="dv">10</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>yyt1789_4_linear <span class="ot">&lt;-</span> <span class="fu">linearity</span>(</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  yyt1789_4, <span class="at">sample =</span> <span class="st">"level"</span>, <span class="at">result =</span> <span class="st">"result"</span>, <span class="at">x =</span> <span class="st">"dilution"</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"linear"</span>, <span class="at">weights =</span> <span class="st">"equal"</span>, <span class="at">adl_rel =</span> <span class="dv">10</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>YY/T 1789.4–2022 Appendix A.5: final line and relative bias</caption>
<colgroup>
<col style="width: 47%">
<col style="width: 28%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Standard location</th>
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Standard</th>
<th style="text-align: right;">ivdtools</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 1</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">4.28</td>
<td style="text-align: right;">4.284</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 1</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">6.07</td>
<td style="text-align: right;">5.974</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 2</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">19.40</td>
<td style="text-align: right;">19.401</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 2</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">5.05</td>
<td style="text-align: right;">5.046</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 3</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">34.52</td>
<td style="text-align: right;">34.518</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 3</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">4.46</td>
<td style="text-align: right;">4.453</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 4</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">64.75</td>
<td style="text-align: right;">64.752</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 4</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">-3.69</td>
<td style="text-align: right;">-3.697</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 5</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">125.22</td>
<td style="text-align: right;">125.219</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 5</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">7.25</td>
<td style="text-align: right;">7.250</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 6</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">246.16</td>
<td style="text-align: right;">246.154</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 6</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.467</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 7</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">367.10</td>
<td style="text-align: right;">367.089</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 7</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">3.77</td>
<td style="text-align: right;">3.773</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 8</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">488.04</td>
<td style="text-align: right;">488.025</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 8</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">-4.04</td>
<td style="text-align: right;">-4.043</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 9</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">608.98</td>
<td style="text-align: right;">608.960</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 9</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">-3.05</td>
<td style="text-align: right;">-3.051</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 10</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">729.92</td>
<td style="text-align: right;">729.895</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 10</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">3.59</td>
<td style="text-align: right;">3.598</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 11</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">850.86</td>
<td style="text-align: right;">850.830</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 11</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">-3.99</td>
<td style="text-align: right;">-3.990</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 12</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">971.80</td>
<td style="text-align: right;">971.765</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 12</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: right;">2.607</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 13</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">1092.74</td>
<td style="text-align: right;">1092.700</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 13</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">-3.20</td>
<td style="text-align: right;">-3.198</td>
</tr>
<tr class="odd">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 14</td>
<td style="text-align: left;">final-line prediction</td>
<td style="text-align: right;">1213.68</td>
<td style="text-align: right;">1213.635</td>
</tr>
<tr class="even">
<td style="text-align: left;">YY/T 1789.4 Appendix A.5 / level 14</td>
<td style="text-align: left;">relative bias (%)</td>
<td style="text-align: right;">2.56</td>
<td style="text-align: right;">2.566</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The model-selection procedures are not identical: the standard fits polynomials to level means and reports regression standard errors, whereas linearity(method = “polynomial”) currently fits individual observations and labels this mode as the legacy EP6-A exploratory workflow; the degrees of freedom and regression standard errors differ. This case therefore calls the package’s linear method a reproduction of the final line only and does not present its polynomial selection as YY/T 1789.4’s higher-order significance test.</p>
<p>The ADL-PctBnd critical table in standard Appendix A.3 also combines regression imprecision, number of levels, and replicate count. adl_rel = 10 is a level-wise numerical limit and does not implement the PctBnd lookup rule. The two similarly named ADL concepts use different algorithms and must be distinguished in reporting.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./013-精密度分析.html" class="pagination-link" aria-label="Precision Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Precision Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./015-定性分析与C5C95.html" class="pagination-link" aria-label="Qualitative Analysis and C5/C95">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Qualitative Analysis and C5/C95</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/hiox-tech/ivdtools/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>